### ISSUE TITLE
Does saspy support winlocal config on WSL (windows subsystem for linux) python?

### ISSUE THREAD

**Issue by blairqin** [sassoftware/saspy#286] opened 2020-03-03 04:25 UTC
**Describe the bug**
I followed instructions from [https://sassoftware.github.io/saspy/](https://sassoftware.github.io/saspy/) to config winlocal using wsl (windows subsystem for linux) python and encountered the following problem.

**To Reproduce**
Here is my sascfg_personal.py (I have copied all the files into one folder.)
```python
SAS_config_names=['winlocal']
# build out a local classpath variable to use below for Windows clients   CHANGE THE PATHS TO BE CORRECT FOR YOU\R INSTALLATION
cpW  =  r"/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.svc.connection.jar"
cpW += r":/usr/local/lib/python3.7/dist-packages/saspy/jar_files/log4j.jar"
cpW += r":/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.security.sspi.jar"
cpW += r":/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.core.jar"
cpW += r":/usr/local/lib/python3.7/dist-packages/saspy/jar_files/saspyiom.jar"

# These jars provide CORBA support for Java 10+ which no longer provides CORBA itself.  CHANGE THE PATHS TO BE C\ORRECT FOR YOUR INSTALLATION
cpW += r":/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-internal-api.jar"
cpW += r":/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-omgapi.jar"
cpW += r":/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-orb.jar"
cpW += r":/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-basic.jar"
cpW += r":/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-tf.jar"
winlocal = {'java'      : '/usr/bin/java',
            'encoding'  : 'windows-1252',
            'classpath' : cpW,
            'javaparms' : ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=sas.exe']
            }
```

**Screenshots**
```python
>>> saspy.version
<module 'saspy.version' from '/usr/local/lib/python3.7/dist-packages/saspy/version.py'>
>>> saspy.SASsession()
Using SAS Config named: winlocal
We failed in getConnection
The native implementation module for the security package could not be found in the path.
SAS process has terminated unexpectedly. Pid State= (5328, 64000)
SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program /usr/bin/java with the following parameters:['/usr/bin/java', '-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=sas.exe', '-classpath', '/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.svc.connection.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/log4j.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.security.sspi.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.core.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/saspyiom.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-internal-api.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-omgapi.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-orb.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-basic.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-tf.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '5770', '-stdoutport', '5771', '-stderrport', '5772', '-zero', '-lrecl', '1048576', '']

Be sure the path to sspiauth.dll is in your System PATH

No SAS process attached. SAS process has terminated unexpectedly.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/saspy/sasbase.py", line 485, in __init__
    pyenc = sas_encoding_mapping[self.sascei]
KeyError: 'No SAS process attached. SAS process has terminated unexpectedly.'
```

**Desktop (please complete the following information):**
 - OS: WSL Debian
 - SAS Version: 9.4M6
 - SASPy Version: 3.2.0

**Comment by tomweber-sas** [comment] 2020-03-03 13:38
Hmmm, well I have no idea if this will work. I had to google WSL to see what it was about, I haven't used it before. I see that you will be executing Python and Java in this Linux environment. In and of themselves, that should not be a problem. However, I don't know how this works regarding Linux executables 'reaching back' into the windows environment works. I assume you have SAS installed on the actual Windows side, right? 
The problem you are getting right now however, is:
```
The native implementation module for the security package could not be found in the path.

which is the issue of

Be sure the path to sspiauth.dll is in your System PATH
```
So, the IOM java libraries are trying to start SAS, but this is the first issue that is causing a failure.
Is the directory containg sspiauth.dll in the system PATH variable, per the instructions? Even if it is, I can't say whether this will actually work. I don't know what the integration level between these two environments (linux and windows) really is, as far as trying to run things across the boundary. It might work! Can you check this first error and then see what happens next? 

BTW, this is issue # 3 in https://sassoftware.github.io/saspy/troubleshooting.html#iom-specific-errors

Thanks,
Tom

**Comment by blairqin** [comment] 2020-03-04 02:32
Thanks for your reply.

Yes, my SAS is installed on windows.

I tried to add `/SASHome/SASFoundation/9.4/core/sasext/` into `PATH` in the following ways but the same problem still exisits.

```python
>>> import os
>>> os.environ["PATH"] += r":/mnt/c/Program Files/SASHome/SASFoundation/9.4/core/sasext/"
>>> import saspy
>>> saspy.SASsession()
Using SAS Config named: winlocal
We failed in getConnection
The native implementation module for the security package could not be found in the path.
SAS process has terminated unexpectedly. Pid State= (622, 64000)
SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program /usr/bin/java with the following parameters:['/usr/bin/java', '-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=sas.exe', '-classpath', '/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.svc.connection.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/log4j.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.security.sspi.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.core.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/saspyiom.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-internal-api.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-omgapi.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-orb.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-basic.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-tf.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '3870', '-stdoutport', '3871', '-stderrport', '3872', '-zero', '-lrecl', '1048576', '']

Be sure the path to sspiauth.dll is in your System PATH

No SAS process attached. SAS process has terminated unexpectedly.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/saspy/sasbase.py", line 485, in __init__
    pyenc = sas_encoding_mapping[self.sascei]
KeyError: 'No SAS process attached. SAS process has terminated unexpectedly.'
```

Apart from these, I tried to execute java commands in the shell. It returns connection refused and the results are as follows.

```shell
export PATH=$PATH:/mnt/c/'Program Files'/SASHome/SASFoundation/9.4/core/sasext
/usr/bin/java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=sas.exe -classpath /usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.svc.connection.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/log4j.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.security.sspi.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.core.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/saspyiom.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-internal-api.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-omgapi.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-orb.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-basic.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-tf.jar pyiom.saspy2j -host localhost -stdinport 3681 -stdoutport 3682 -stderrport 3683 -zero -lrecl 1048576
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:493)
        at java.base/sun.nio.ch.Net.connect(Net.java:482)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
        at java.base/java.net.Socket.connect(Socket.java:603)
        at java.base/java.net.Socket.connect(Socket.java:552)
        at java.base/java.net.Socket.<init>(Socket.java:475)
        at java.base/java.net.Socket.<init>(Socket.java:249)
        at pyiom.saspy2j.main(saspy2j.java:171)
Exception in thread "main" java.lang.NullPointerException
        at pyiom.saspy2j.main(saspy2j.java:180)
```

**Comment by tomweber-sas** [comment] 2020-03-04 02:43
Yeah, that's where I'mnot sure about the interaction between linux code and windows code, when the code expects to be running in the windows side (the sspi stuff, for sure). What you tried is what I would try, though I think I would also put the path in the actual windows PATH environment variable, as it will/would be executing in the windows side, not the linux side.
The case where you tried it in the terminal is what I'd expect, and good job trying that. The error there is that the java side is trying to connect back to saspy, which isn't there. That verifies that enough of the classpath is correct for the java code to get that far. The problem is that the sspi problem is past that point. So, it doesn't get to that point in the code itself.
Can you put the path in the real Windows system PATH and see if that happens to make any difference? I just don't know what to expect in this hybrid environment.

Thanks,
Tom

**Comment by blairqin** [comment] 2020-03-04 03:06
Thanks for your reply.

I put `C:\Program Files\SASHome\SASFoundation\9.4\core\sasext\` into system PATH like this.

![image](https://user-images.githubusercontent.com/41547690/75840548-a0068380-5e1f-11ea-98ad-10dd40b8924f.png)

After that, I tried to run `saspy` on WINDOWS python and it works well.

```python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> saspy.SASsession()
Using SAS Config named: autogen_winlocal
SAS Connection established. Subprocess id is 10444

The encoding value provided doesn't match the SAS session encoding.
SAS encoding is utf-8. Specified encoding is windows-1252.
Using encoding utf_8 instead to avoid transcoding problems.
You can override this change, if you think you must, by changing the encoding attribute of the SASsession object, as follows.
If you had 'sas = saspy.SASsession(), then submit: "sas._io.sascfg.encoding='override_encoding'" to change it.   
Access Method         = IOM
SAS Config name       = autogen_winlocal
SAS Config file       = C:\Python38\lib\site-packages\saspy\sascfg_personal.py
WORK Path             = C:\Users\Blair\AppData\Local\Temp\SAS Temporary Files\_TD9208_LING-MACBOOK-PR_\Prc2\     SAS Version           = 9.04.01M6P11072018
SASPy Version         = 3.2.0
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 9208
```

After that, I restarted WSL i.e. restart LxssManager service. However, the same problem exists after I switched into WSL python. And the results are as follows.

```python
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ["PATH"] += r":/mnt/c/Program Files/SASHome/SASFoundation/9.4/core/sasext/"
>>> import saspy
>>> saspy.SASsession()
Using SAS Config named: winlocal
We failed in getConnection
The native implementation module for the security package could not be found in the path.
SAS process has terminated unexpectedly. Pid State= (59, 64000)
SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program /usr/bin/java with the following parameters:['/usr/bin/java', '-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=sas.exe', '-classpath', '/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.svc.connection.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/log4j.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.security.sspi.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.core.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/saspyiom.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-internal-api.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-omgapi.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-orb.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-basic.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-tf.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '4209', '-stdoutport', '4210', '-stderrport', '4211', '-zero', '-lrecl', '1048576', '']

Be sure the path to sspiauth.dll is in your System PATH

No SAS process attached. SAS process has terminated unexpectedly.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/saspy/sasbase.py", line 485, in __init__
    pyenc = sas_encoding_mapping[self.sascei]
KeyError: 'No SAS process attached. SAS process has terminated unexpectedly.'
```

And the java results from the shell are as follows.

```shell
export PATH=$PATH:/mnt/c/'Program Files'/SASHome/SASFoundation/9.4/core/sasext 
/usr/bin/java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=sas.exe -classpath /usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.svc.connection.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/log4j.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.security.sspi.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/sas.core.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/saspyiom.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-internal-api.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-omgapi.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/glassfish-corba-orb.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-basic.jar:/usr/local/lib/python3.7/dist-packages/saspy/jar_files/pfl-tf.jar pyiom.saspy2j -host localhost -stdinport 3681 -stdoutport 3682 -stderrport 3683 -zero -lrecl 1048576

java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:493)
        at java.base/sun.nio.ch.Net.connect(Net.java:482)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
        at java.base/java.net.Socket.connect(Socket.java:603)
        at java.base/java.net.Socket.connect(Socket.java:552)
        at java.base/java.net.Socket.<init>(Socket.java:475)
        at java.base/java.net.Socket.<init>(Socket.java:249)
        at pyiom.saspy2j.main(saspy2j.java:171)
Exception in thread "main" java.lang.NullPointerException
        at pyiom.saspy2j.main(saspy2j.java:180)
```

Thanks,
Leo

**Comment by tomweber-sas** [comment] 2020-03-04 03:11
So, I'm not convinced that this can actually work, just thinking about it here for a bit longer. For sure, add the path in the windows PATH and see what happens, but here's what I'm picturing in my head; again, not knowing much about this WSL, but understanding computer science.
I don't doubt that this WSL environment can access the windows file system, that's easy. However, the linux side of this is linux and executes linux executables. It is linux and I can't believe that they have somehow wrangled it to be able to execute windows executables inside that linux system. For instance, saspy's java process which it starts up to run the IOMclient code is a linux process. That process is trying to load the IWA (itegrated windows authentication) code to authenticate your ID to do the IOM connection to start SAS. It's trying to load the sspiauth.dll (dot DLL), but that can't run in a linux process. There would have to be an equivalent .so file, which there isn't. The Linux process itself can't load a .dll. I don't believe that can be done. Now inter-process communication between a windows process and a linux process, in this windows/WSL environmentf, I can believe would work, same as filesystem integration. But executing shared libraries of opposite architectures, I don't believe is something they've  built into this. Again, I could be wrong, and I don't know. But, this is where I believe this will fail trying to do this. I believe that if you were trying to connect to a remote IOM server, where loading this sspiauth.dll in the java code wouldn't happen, that you would be able to use this client in the WSL environment. But as IOM requires the sspiauth.dll for the local windows mode of running SAS, this can't work. 
But, let's see if I might be wrong and it works! :)  That would be ok too.
Tom

**Comment by tomweber-sas** [comment] 2020-03-04 03:14
Ah, you tried it. Well, yep, that's what I was expecting. Yes, this should work fine when you are running your python/java processes on windows, where the .dll can be executed. But it can't run in a linux process. And, there is no linux .so version of that library to be able to use w/in a linux process.

**Comment by tomweber-sas** [comment] 2020-03-04 03:16
I hope my explanation, or ramblings, makes sense. It's late here and I'm a little bleary eyed. Probably have a lot of typos too :)
I'm glad you can run on the windows side, at least. I'm sure it would be nice to run on linux instead.I prefer that myself too.
Thanks,
Tom

**Comment by blairqin** [comment] 2020-03-04 03:28
Thanks for your reply.

Maybe we can close this issue now given that I can use saspy on windows python and there is no equivalent .so file.

Again, thanks for your help and I greatly appreciate it.

Best,
Leo

**Comment by tomweber-sas** [comment] 2020-03-06 00:59
Sure thing, yeah, I wish there was a Linux version of that, but it's a Windows specific thing, so there just isn't. Glad your running though, even if you have to use Windows, but it is SAS Windows, so there's that. I'll close this. Let me know if your need anything else!
Tom

**Closed by tomweber-sas** 2020-03-06 00:59 UTC
