### ISSUE TITLE
df2sd() transcoding error persists after changing sasv9.cfg

### ISSUE THREAD

**Issue by yam3moe** [sassoftware/saspy#481] opened 2022-08-31 21:57 UTC
Hi,

After finally being able to establish a local connection, I ran into another encoding issue with df2sd().
I am aware that there was a similar issue [posted here](https://github.com/sassoftware/saspy/issues/268) before. So, I followed the steps in adding utf8 coding support. (screenshot below)

![sas encoding aldy changed to u8](https://user-images.githubusercontent.com/74246882/187791327-782f564e-1147-4861-a114-a734303ae6db.png)

However, when I ran df2sd again after changing the encoding in sasv9.cfg, the issue hasn't gone away. 
  
![image](https://user-images.githubusercontent.com/74246882/187791727-0ae6d962-76a1-428b-ab2b-8c5711244108.png)

Now, I understand that I could use _encode_errors_ set to 'replace' or 'ignore' to force conversion. Despite that, I am interested to learn which is causing the problem, so I would appreciate your kind explanation to a newbie.

The photos below show what values are in row 125597 and types of each variable.

![image](https://user-images.githubusercontent.com/74246882/187792210-bb935426-ff4e-430c-90bc-e461626928cb.png)

![image](https://user-images.githubusercontent.com/74246882/187792254-c172008c-3ac4-4219-a119-62d6ba74e54f.png)

Thanks :-)

**Comment by tomweber-sas** [comment] 2022-09-01 13:11
Yes you're right that it's better to understand what's going on than to try to just hide the errors. Can you submit your SASsession object so I can see what encoding SAS is running in? We can verify the change to your v9config actually did what you expect. 
Thanks,
Tom

**Comment by yam3moe** [comment] 2022-09-02 17:44
Hi Tom,

here is the SAS session object. Thanks. 

![image](https://user-images.githubusercontent.com/74246882/188208888-cc68795f-1ac8-4cf3-b638-ad9163f9aaa6.png)

**Comment by tomweber-sas** [comment] 2022-09-07 17:21
Hey, thanks, that looks like SAS is running in utf-8, so that's good. This means that if you are getting a transcode error still, that it's going to be due to a multi-byte character being truncated or something like that in the dataframe. df2sd() builds out blocks of rows to send over, defaulting to 32k, so the message about on or before a row is when the block is ready to transfer and I try to encode/decode it on the python side. To try and find out what row actually has the problem data in it, you can add an option and set the blocksize to 1 row at a time, and then the encoding error should be for the specific row it states.

'sd = sas.df2sd(dataframe, 'tablename', blocksize=1)'

Then when it says the row number, it should be that row (1 based, not 0 based). So give that a try, it will be slower of course, but it should give us the row that has an issue. Then we need to look at the character columns and see where this bad char is.
You can try to encode() the char values for the row and see the transcoding error, since it's the python encode error this is getting.

**Comment by yam3moe** [comment] 2022-09-12 15:17
Hi,
Apology for the late reply. Today, I went back to address this issue and strangely enough, I am not having any problem with df2sd(). Following the steps you suggested, this is what I get and it looks like the conversion from df to sas_dataset was successful. Am I right? Do you see any other problem that might have happened in conversion stage? Thanks.

![image](https://user-images.githubusercontent.com/74246882/189691607-51deeab0-b4cf-4206-a390-3a8fc03b1e98.png)

**Comment by tomweber-sas** [comment] 2022-09-12 17:56
Well, if that (specifying blocksize=1) is keeping it from happening, it sort of implies it could be a bug in my code. That 'shouldn't have' fixed the problem. Can you run the following for me and show the output?
`sas.df_char_lengths(dataset)`
Thanks,
Tom

**Comment by yam3moe** [comment] 2022-09-14 00:15
Hi Tom,

It seems that even if I don't use blocksize=1, the conversion still went without errors (as you can see in the photo below). and you can see the output for the line `sas.df_char_lengths(dataset)`

![image](https://user-images.githubusercontent.com/74246882/190031148-20215bec-e731-48e9-a8be-dd0be7a55bb8.png)

**Comment by tomweber-sas** [comment] 2022-09-14 01:59
well, that seems as though there was something happening with the dataframe you had before. I've looked at the code again and can't see a reason for it to have caused the error before. Multi-byte characters fields being truncated is the most usual cause for this kind of thing. I don't know how you created the dataframe, so that's the most likely possibility. Even PROC IMPORT in SAS reading a CSV file  to create a SAS dataset will make this happen if you don't know to force it to get the column lengths right. So, the most likely cause for this is somehow having data get compromised in the dataframe. 
How do you create the dataframe? Has the contents changed across these different attempts?

**Comment by yam3moe** [comment] 2022-09-18 19:27
Hi Tom,

I am not sure at what stage of data reading and conversion might have interrupted with the saspy. The starting file I have for this project is a text file where values are wrapped in pipe characters and fields are comma delimited. Part of it is shown in the photo below. I read it into SAS dataset. Then, it happened that I have to do string matching between company names in the dataset and company names in another finance dataset from which I desire to extract asset returns. Since I am quite new to SAS and no idea how to do strings matching in SAS, I converted the SAS dataset into panda dataframe. Thereafter, I will have to reconvert it into SAS dataset for my colleagues to use since python is not widely used in where I am. So, where do you think the root of the problem may have occurred?

![image](https://user-images.githubusercontent.com/74246882/190924603-ddb150be-c92c-4b7a-9825-3f01bc9aa45e.png)

And this is how I imported it into SAS dataset. I didn't write it, someone helped me when I posted my question on SAS forum.
 
![image](https://user-images.githubusercontent.com/74246882/190924835-0f934772-6749-4cd6-a1fb-6b66fc25c5d0.png)

And I read it in python using
`df1 = pd.read_sas(r"path/all_trans_nopipes.sas7bdat", encoding = 'LATIN-1');`

**Comment by yam3moe** [comment] 2022-09-25 23:10
> SAS is running in UTF-8 (if it's what you changed to), so anything that's not ASCII will become multibyte characters. Truncating a multi-byte character will certainly cause this problem.
> 
Hi Tom, I read the original data (in txt file not CSV) into SAS dataset a few months ago. At that time, I haven't changed the encoding to utf-8. I changed it to utf-8 when the problem with transcoding error happened 25 days ago (that is when I opened this thread).

> Have you verified the data in the SAS data set that you get from these data steps to begin with?
> 
I am a little dumb here. What do you mean by verifying? I scanned through the first few rows of SAS dataset and visually inspected if the data from the text file was correctly read into SAS dataset. It seems to my eyes that the operation went smoothly. Could you please elaborate on this point?

> Next, using Pandas read_sas and telling it the data is latin1 is the next place things could go wrong. read_sas from Pandas isn't something that's supported by SAS nor is it necessarily correct for how to read SAS data sets. So, this is another place where there's no telling what's being done, especially with telling it the data is latin1 if it's really utf-8. What happens when you use sas.sd2df() to read the data set into a data frame?
> 
Sorry, I should have given you a little bit of background. As I said above, in the beginning, I was not using saspy. 
- First, I read the raw text file into SAS dataset. 
- Afterwards, I read it into pandas dataframe using `df1 = pd.read_sas(r"path/all_trans_nopipes.sas7bdat", encoding = 'LATIN-1');` and did some string matching in Python. I used LATIN-1 at that time because without it, pandas would throw an error. Perhaps, SAS encoding before I changed to utf-8 was LATIN-1. I can't remember exactly though.
- With string matching done, I wanted to convert back the panda dataframe into SAS dataset. Because I needed it to convert into csv first, then into sas7bdat, I find it cumbersome and decided to use SASPY package. Now that SASPY is working (hopefully), I will probably redo my steps and use `sas.sd2df` instead of `read_sas`.

> Is this csv file fixed (static) or is it something that is changings over time? If you have a copy that gets the error (you seemed to run with something that didn't cause the error last time), then you could track it down, though that's a little tedious, but that's what would be needed. Unfortunately SAS doesn't do a good job of validating characters; it really only deals with bytes; so it won't catch these issues itself. It's when you need to transfer data between external sources that those layers of code have to deal with characters, not just bytes, and these problems arise.
The file is fixed, I downloaded it from a website three months ago and has since been sitting in my local drive.

Thanks for your help as always.

**Comment by tomweber-sas** [comment] 2022-09-26 18:46
ok, thanks for that info. Though, I'm not really sure what else I can do at this point. The original error was about some byte being 0x8A which is neither a utf-8 character, not a latin1 character. But after some back and forth you said that it doesn't fail anymore and it's working. I really don't know all that's transpired with this, so I don't know how the original problem happened nor why it doesn't fail anymore. Working with encodings and transcode data between different encodings isn't something everyone's well versed in. In many ways, SAS contributes to these problems in that it doesn't validate characters, it just processed bytes, for the most part. Then, changing encodings (just telling different software components that data encoding is something that is may or may not be), can cause other problems down the line.

My best suggestion is to start with a clean process of what you're trying to do, understanding the data you have to start with (what encoding was it?) and then understanding the process you're using and see if you get valid data. If not, tracking it down so you know what the problem is, isn't the simplest thing in the world, but it's what needs to happen to understand where the problem was.

**Comment by tomweber-sas** [comment] 2022-10-03 14:26
file_copy takes 2 file names. So you copied the t1 file to a file named work. Why wouldn't you simply assign a libref to the directory t1 is in and use that? There's no reason to try to copy the file to the work library just to access it.

**Comment by tomweber-sas** [comment] 2022-10-07 18:14
Hey, do you think we can close this? The issue was the truncated data in your dataframe that can't be reproduced, based upon an unclear creation path. These other issues or questions have been about incorrect use of the api and being new to SAS; not understanding the SAS side of things enough to accomplish what you're trying to do. I don't mind helping, but as an issue goes, this has kind of gone off on tangents.
Thanks!
Tom

**Comment by tomweber-sas** [comment] 2022-10-07 18:22
Cool, feel free to open other other issues if you need to! I'm always happy to help as best I can!
Thanks,
Tom

**Closed by tomweber-sas** 2022-10-07 18:22 UTC
