### ISSUE TITLE
Cannot Install saspy on the Win10

### ISSUE THREAD

**Issue by RunnerupWang** [sassoftware/saspy#33] opened 2017-05-07 06:16 UTC
Hello,
I have both  **SAS 9.4 TS1M2** and **pyton 3.6** installed on my PC, and my OS is **WIN10**.
I follow the instructions in the **Installation** section of this website, that is 
"WIN+R"  --> cmd --> `C:\Users\汪亚军>pip install `
However, it generates the following note and error message, please help me figure out what's wrong,thanks a lot.

**************************************************************************************************************
Collecting saspy
  Using cached saspy-**2.1.4.tar.gz**
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 17: invalid continuation byte**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\program files\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 17: invalid continuation byte**
**********************************************************************************************************

**Comment by tomweber-sas** [comment] 2017-05-08 13:37
I'm a little confused at this reference:
"WIN+R" --> cmd --> C:\Users\汪亚军>pip install
But, this error can be caused when python processes a windows path that contains '\U' or '\u' as it takes that as a unicode escape sequence, trying to use the next characters as a hex value for a unicode code point. I cna't tell from the traceback where this is happening; it appears to be in pip. Can you pip install other packages?

**Comment by RunnerupWang** [comment] 2017-05-08 14:43
Hi,tomweber

WIN+R   is the windows command shortcut
cmd is to trigger the shell window
C:\Users\汪亚军  is my PC default path
pip install saspy is the dos command to download and install packages

I can install other packages, such as Numpy.
I am from China, the default system language is Simplified Chinense, I wonder if this matters.

**Comment by tomweber-sas** [comment] 2017-05-09 00:54
Ok, understand the WIN+R...  Thanks. 
As I haven't seen this with the install, I do think it could be something to do with the encoding. I will look through the install for anything that could cause this. 

One thing you can try is to get the lastest code from the repo, should be 2.1.5. we are about to promote that to pypi as the new install. That way we are using the same code. Plus it has a number of fixes.

**Comment by RunnerupWang** [comment] 2017-05-09 09:51
Hi,tomweber

I've already tried to download the newest version 2.1.5, but it still fails at installation.

**Comment by tomweber-sas** [comment] 2017-05-09 13:41
Ok, thanks. I'll try to track this down today!

**Comment by tomweber-sas** [comment] 2017-05-09 18:26
Well, I don't see anything in saspy that I can account for this. We don't really *do* anything in the install, so there's no windows paths issue or other unicode things I can see. Googling the error though, shows this same issue with other packages. None really had a good answer, but this one sure looks close. https://github.com/zopefoundation/zope.interface/issues/76
It shows the same error in pip\compat\__init__.py in the same call: return s.decode(sys.stdout.encoding)

There is also a comment in there about the console encoding having been changed in that version which could be causing the problem. I don't really see an answer in there though, about how to solve this. 

Ah, here's a better issue, with pip itself: https://github.com/pypa/pip/issues/4251. I do think this is probably the issue you are hitting. 

Can you check into those issues and see if there is something you find to work around that pip problem?
They do hint around at some possible workarounds and maybe there's a fix from this issue:https://github.com/pypa/pip/pull/4310

But as I can't reproduce this, maybe you can see if any of these pip issues provide you a fix or work around that will get you going. They also seem to refer to this as the start of the problem: PEP 528  https://docs.python.org/3/whatsnew/3.6.html#pep-528-change-windows-console-encoding-to-utf-8

**Comment by tomweber-sas** [comment] 2017-05-16 16:06
We're you able to resolve this and install and use saspy on your system?

**Comment by RunnerupWang** [comment] 2017-05-17 10:21
I am a little busy now, and I have not tested your suggestions. I will have a try in the weekend, and reply to you thereafter.

**Comment by tomweber-sas** [comment] 2017-05-17 13:06
Ok, no problem. It appears this problem was introduced in 3.6, so it might be easy enough to install 3.5 and see if it just works with that. as an alternative if none of these other workarounds pan out.

**Comment by RunnerupWang** [comment] 2017-05-20 04:40
Hi，Tomweber
It really works in Python 3.5.4, thanks a lot.

**Comment by tomweber-sas** [comment] 2017-05-22 15:13
That's great. Hopefully, they will fix that problem in 3.6 pip install soon. Let me know if you have any other issues or suggestions! I'll go ahead and close this. 

Thanks!
Tom

**Closed by tomweber-sas** 2017-05-22 15:13 UTC
