### ISSUE TITLE
INPUT statement exceeded record length error when using df2sd

### ISSUE THREAD

**Issue by DataRevelation** [sassoftware/saspy#322] opened 2020-09-24 22:04 UTC
I am getting this error when I try to convert a pandas dataframe to SAS data set using df2sd whenever there is an empty string in the dataframe. 

I am using saspy 3.51 with SAS 9.4

**Comment by tomweber-sas** [comment] 2020-09-24 23:57
Well that won't do. It looks like I broke this in 3.5.0. I reworked sd2df and df2sd to account for some other issues and got them working so well! Or so I thought :) . I didn't have an empty string in my test data for the change, it was having to do with embedded quotes and delimiters and stuff, and I missed this case in the code I reworked. I see the same error, plain as day. I've added the necessary:  'or len(var) == 0' to catch this and added an empty sting to my test data and manually verified this, as well as reran the tests (with the new data) and the problem is fixed. 

Really sorry about breaking that, but it sure is nice to be able to fix a problem as quickly as you can cause one :)   I've push this and built a new release with it so others don't get bit by this (or as few as possible). It is be V3.5.3 and should is available on the saspy repo, and on Pypi. Conda will take a little while as it's an automated build that gets triggered after seeing the new version out there on the other site.

Can you:
```
pip uninstall -y saspy
pip install saspy
```
and see that it's fixed and working as it used to? 

Sorry about that but you should be good now!
Tom

**Comment by DataRevelation** [comment] 2020-09-25 00:37
wow, identifying and fixing the issue within 2 hours. You rock !!

**Comment by tomweber-sas** [comment] 2020-09-25 00:55
We'll, I broke it! And, have you verified it's fixed? Just cuz I said... I still want to see that it's fixed from your side.

**Comment by DataRevelation** [comment] 2020-09-25 01:00
No, It will take a few days for my company to approve a new package. I will confirm as soon as I can. Thanks.

**Comment by tomweber-sas** [comment] 2020-09-25 12:17
Ok, sorry about that, I'll leave this open until you can confirm the fix on your end.
Thanks,
Tom

**Comment by DataRevelation** [comment] 2020-09-28 22:07
I tested 3.5.3, and the empty string issue is fixed. Thanks. Great work.

**Comment by tomweber-sas** [comment] 2020-09-29 00:21
That's great! And thanks for confirming that. I'll go ahead and close this, and again, sorry for breaking you there!
Thanks!
Tom

**Closed by tomweber-sas** 2020-09-29 00:21 UTC
