### ISSUE TITLE
referencing a library in magic cell

### ISSUE THREAD

**Issue by Rhadadi** [sassoftware/saspy#52] opened 2017-08-17 00:22 UTC
I created a sas session as 

`sas_session1 = saspy.SASsession(cfgname='winlocal')
sas_session1.saslib('Sprd',  path="J:\Oea\OAM\Projects\ETF_Registration\Data")`

and converted a pandas data frame to sas dataset using 
`UScategory_sas = sas_session1.df2sd(UScategory, libref='Sprd')`.

 `UScategory_sas.head()` shows that I have converted the pandas dataframe successfully to sas dataset. But when I am trying to use the dataset in a magic cell, it does not work. I checked the
 
`sas_session1.datasets(libref= 'Sprd') ` 
and I was not able to locate the UScategory_sas dataset .
running a simple SAS code below shows "ERROR: Libref SPRD is not assigned."

`%%SAS sas_session1
data UScategory_sas2;
set Sprd.UScategory_sas;
run;` 

`submit `command, however, works well but I would prefer to run the codes in a `%%SAS` magic cell.

`results = sas_session1.submit("proc print data=Sprd.UScategory_2;run;")
HTML(results['LST'])`

I would appreciate if you could comment why magic cell has  a different session although I use `%%SAS sas_session1` .
Thanks

![image](https://user-images.githubusercontent.com/11033482/29390444-67459782-82be-11e7-8960-6deb4c2d56b0.png)

**Comment by jld23** [comment] 2017-08-17 02:44
@Rhadadi this issue is a duplicate of #26. There is a code fix in that issue that I think @jasonphillips is making a PR.

Jared

**Comment by Rhadadi** [comment] 2017-08-17 03:25
@jld23

Thanks Jared for your response and your code.
What is the best way to use the code? My guess is to create a .py file and leave it in saspy folder and run it at the top of my Jupyter notebook. 

And,
When I attempted to convert a large dataframe (2 miilion by 10 columns) to a sas dataset, after 20 minutes I get an error that says sas was enforced to be shut down. Is there any limit for sas connection using saspy?

**Comment by jld23** [comment] 2017-08-17 03:37
@Rhadadi the quickest way is to take the code from #26 and replace the functions in sas_magic.py until we get a PR and create a new pip.
There are no hard limits set for the dataframe conversion. Can you provide more details so that we can try and track down the issue?
Which interface (IOM, STDIO, etc)
SAS Version
Host (windows, linux, etc)

Most of this can be obtained from the SAS session object

```
conn = saspy.SASsession()
conn
```

**Comment by Rhadadi** [comment] 2017-08-17 03:57
the error message is 
`ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host`
 I tried several times to convert that dataframe and I got the same error.
 
Access Method         = IOM
SAS Config name       = winlocal
WORK Path             = C:\...
SAS Version           = 9.04.01M3P06242015
SASPy Version         = 2.1.6
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = WLATIN1
Python Encoding value = windows-1252

**Comment by Rhadadi** [comment] 2017-08-21 15:59
@tomweber-sas
Tom: Did you have any thought on this?

**Comment by tomweber-sas** [comment] 2017-08-22 20:03
I'm sorry, I'm on vacation till next week and don't have a computer with me to investigate. Will look into this when I get back.
Tom

**Comment by tomweber-sas** [comment] 2017-08-28 13:42
@Rhadadi , I'm back in the office. There were a couple of fixes pushed to the dataframe2sasdata methods right before I left for vacation a couple weeks a go #50. They had to do with missing values in the data frame that causes problems loading into the SAS Data Set. It's possible you may be hitting that. Can you look in the saslog and see if there were errors for this step? The SASsession object has a saslog() method you can use to see the log. given sas = SASsession(), then you can just submit
```
print(sas.saslog())
```
I don't know why you would be getting a connection reset error, but let's see what the log shows us for starters. You may want to try loading a subset of the data frame too, to see what happens. If there are errrors in the log, no need to wait for the whole thing to fail to see them. Also, if it loads part of it without issue, but not all of it, that could be some other issue perhaps. 

Thanks,
Tom

**Comment by jld23** [comment] 2017-09-14 22:36
To the original issue the latest release of saspy 2.1.7 addresses the named magic session. If you're still having issues, you can update `pip install saspy -U` . If the issue still exists, please post the results of your `print(sas.saslog())` call so we can see why SAS is unhappy.

**Comment by Rhadadi** [comment] 2017-09-26 22:55
After updating the Saspy, the conversion to DataFrame works well. . Thanks Tom and Jared!

**Comment by tomweber-sas** [comment] 2017-09-27 11:38
That's great! Thanks for the update. I'll go ahead and close this issue. Let us know if there's anything else!

Thanks,
Tom

**Closed by tomweber-sas** 2017-09-27 11:38 UTC
