### ISSUE TITLE
Categorical variables fail in dataframe2sasdata?

### ISSUE THREAD

**Issue by snoopy369** [sassoftware/saspy#156] opened 2018-08-10 05:12 UTC
I have a DataFrame that I attempted to load to SAS (in 2.2.6) using df2sd, and received a 'Not Implemented' error.  I was able to identify that it failed specifically when I included categorical variables in the dataframe, and succeeded when I converted them to strings.

Is this expected?  Is there a better workaround?  

Thanks!

Here's the code:

```
import stats_can  #https://github.com/ianepreston/stats_can/ 
import pandas as pd
import saspy

statcan_dat =stats_can.table_to_dataframe({'11100011'},path='c:\\temp\\stats-can')

def upload_to_SAS(df,path,sastbl):
    sas = saspy.SASsession(cfgname='winlocal')
    sas.saslib('demo',path=path)
    sas.df2sd(df=df,table=sastbl,libref='demo')

upload_to_SAS(df=statcan_dat,path='c:\\temp',sastbl='statcan_data')
#fails - "not implemented" exception
```

Here's the 'fix':

```
char_cols = statcan_dat.dtypes.pipe(lambda x: x[x == 'category']).index

for c in char_cols:
    statcan_dat[c] =statcan_dat[c].astype(str)
upload_to_SAS(df=statcan_dat,path='c:\\temp',sastbl='statcan_data')
#succeeds
```

**Comment by tomweber-sas** [comment] 2018-08-10 15:36
Great, thanks. I will do that so I can reproduce this and see what to do. I see where the error is coming from. I'm trying to get the length for the character types that I'll be creating in SAS. I am  identifying types that will be char in SAS by looking at the dtype based upon these kinds in the code.
```
The supported kinds are
'?' boolean
'b' (signed) byte
'B' unsigned byte
'i' (signed) integer
'u' unsigned integer
'f' floating-point
'c' complex-floating point
'm' timedelta
'M' datetime
'O' (Python) objects
'S', 'a' zero-terminated bytes (not recommended)
'U' Unicode string
'V' raw data (void)
```
As none of these say anythig about Category, I guess it is probably O for object. But, it appears that pandas can't do a len() on that type and it's failing there. So, I'll install this and see what I can do to mitigate this. 

Thanks,
Tom

**Comment by tomweber-sas** [comment] 2018-08-10 16:07
pip install wouldn't work with either http or ssh. So, I downloaded as a zip and copied to my system.
It installed, and I ran the code, but I'm not sure what the parameters are supposed to be. Here's what I got and the repo directory. Can you tell me what I should have for the parameters for the call?

I'm not sure I've got it right.
Thanks,
Tom

```
Python 3.5.1 (default, Jan 19 2016, 21:32:20)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stats_can  #https://github.com/ianepreston/stats_can/
>>> import pandas as pd
>>> import saspy
>>> statcan_dat =stats_can.table_to_dataframe({'11100011'},path='/u/sastpw/stats_can-master')
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/pandas/core/categorical.py", line 330, in __init__
    codes, categories = factorize(values, sort=True)
  File "/usr/lib64/python3.5/site-packages/pandas/core/algorithms.py", line 471, in factorize
    labels = table.get_labels(values, uniques, 0, na_sentinel, check_nulls)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1352, in pandas._libs.hashtable.PyObjectHashTable.get_labels
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/net/sanyo.unx.sas.com/vol/vol810/u81/sastpw/stats_can-master/stats_can/stats_can.py", line 459, in table_to_dataframe
    df[actual_cats] = df[actual_cats].astype('category')
  File "/usr/lib64/python3.5/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/usr/lib64/python3.5/site-packages/pandas/core/internals.py", line 3457, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/usr/lib64/python3.5/site-packages/pandas/core/internals.py", line 3324, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/lib64/python3.5/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/usr/lib64/python3.5/site-packages/pandas/core/internals.py", line 594, in _astype
    return self.make_block(Categorical(self.values, **kwargs))
  File "/usr/lib64/python3.5/site-packages/pandas/core/categorical.py", line 342, in __init__
    raise NotImplementedError("> 1 ndim Categorical are not "
NotImplementedError: > 1 ndim Categorical are not supported at this time
>>>
>>>
tom64-3> ll
total 4184
drwxr-xr-x   4 sastpw r&d    4096 Aug 10 12:00 .
drwxr-xr-x 229 sastpw r&d   98304 Aug 10 11:59 ..
-rw-r--r--   1 sastpw r&d 3971124 Aug 10 12:00 11100011-eng.zip
-rw-r--r--   1 sastpw r&d  121009 Aug 10 12:00 11100011.json
-rwxr-xr-x   1 sastpw r&d   35147 Aug  9 09:06 LICENSE
-rwxr-xr-x   1 sastpw r&d     557 Aug  9 09:06 meta.yaml
-rwxr-xr-x   1 sastpw r&d     930 Aug  9 09:06 README.md
-rwxr-xr-x   1 sastpw r&d     211 Aug  9 09:06 setup.py
drwxr-xr-x   3 sastpw r&d    4096 Aug 10 11:59 stats_can
drwxr-xr-x   2 sastpw r&d    4096 Aug 10 11:59 tests
tom64-3> ll stats_can/
total 32
drwxr-xr-x 3 sastpw r&d  4096 Aug 10 11:59 .
drwxr-xr-x 4 sastpw r&d  4096 Aug 10 12:00 ..
-rwxr-xr-x 1 sastpw r&d   637 Aug  9 09:06 __init__.py
drwxr-xr-x 2 sastpw r&d  4096 Aug 10 11:59 __pycache__
-rwxr-xr-x 1 sastpw r&d 16256 Aug  9 09:06 stats_can.py
tom64-3>
```

**Comment by snoopy369** [comment] 2018-08-10 16:15
Hmm, it looks to me that you have it right - I am on windows not unix, so I hope that's not a difference...  I'm using pandas 0.23.0 in case there's some difference there?  I just ran the same code swapping to a Windows path and it worked correctly.

The first parameter is a table ID (from [statcan's website](https://www150.statcan.gc.ca/n1/en/type/data),  and the table in yours is an actual table.

**Comment by tomweber-sas** [comment] 2018-08-10 20:06
Well, I tried on windows and got the same failure.

My pandas on linux is 
Name: pandas
Version: 0.21.0

and on win, less than that. 


So, looking at the traceback, I see that code is using .astype('category') on these character fields.
I did that to a column in a dataframe and it shows the dtype as 'O'. And, I can then reproduce the error.

So, I've got a fix that I've just pushed to master. I've been validating that I haven't broke anything else trying to get these Category types flowing through. All looks good.

Can you pull master and see that it fixes your case too, as I can't actually run that still.

thanks,
Tom

**Comment by snoopy369** [comment] 2018-08-10 21:53
Looks like that worked.  The only thing I see as odd right now is that the NaNs become "nan" instead of becoming missing, on 'STATUS','SYMBOL','TERMINATED'.  Maybe that's expected though?

**Comment by tomweber-sas** [comment] 2018-08-13 13:27
@snoopy369 good catch. It turns out I wan't checking for NaN's in character columns and was actually writing the character string 'nan' to the SAS Data Set. I've fixed this at master. So, now I believe, you should see the correct behavior.
I've also added support for boolean types as well, to df2sd. They had been just ending up Missing in SAS, but are now 0 or 1 (False / True) so that they can still be used in logical processing. The strange thing with bool was that the documentation for dtype.kind states bool is '?', but that's not what it was. It was showing 'b' which states it's a signed byte. So I had to adjust and just compare dtype == 'bool' which works.

Can you pull master again and verify your Category and NaN values are as you would expect now?
With this, I'll be ready to create a new release (2.2.7) with all of these fixes that are at master.

Thanks!
Tom

**Comment by snoopy369** [comment] 2018-08-13 16:17
Looks good to me, those are now missing  (' ') instead of 'nan'.  Thanks!  (Checked v2.7)

**Comment by tomweber-sas** [comment] 2018-08-13 16:47
Awesome! thanks for verifying it for me. I've built a new 2.2.7 release with all of this.
I'll close this out now. Let me know if you see anything else!
Tom

**Closed by tomweber-sas** 2018-08-13 16:47 UTC
