### ISSUE TITLE
Solaris Support?

### ISSUE THREAD

**Issue by aaronsmith1234** [sassoftware/saspy#368] opened 2021-03-09 23:27 UTC
**Is your feature request related to a problem? Please describe.**
An environment I work with has a Solaris box. We would like to explore using this with our Solaris box, but its not clear if that is a supported platform or not.

**Describe the solution you'd like**
Saspy ability to interact with Solaris instances of SAS server (which may already be possible, just not clear from docs)

**Comment by tomweber-sas** [comment] 2021-03-10 13:51
Well, now that I'm logged on to work, and I can't find a Solaris machine, let me qualify what I said by saying IOM should work without issue. As for STDIO (over SSH if from another machine), I can't prove one way or another so far, as I don't have a Solaris machine to use. Would you be running python locally on that machine, or remotely from another system? I'm trying to find a system to try either on currently. I don't know of a reason it wouldn't, but I can't try it to prove it does. 
Let me know how you're going to try to connect and I'll help you out either way.
Tom

**Comment by tomweber-sas** [comment] 2021-03-10 14:05
Well, I did just finally find a Solaris box w/ SAS on it and used STDIO over SSH (I don't have access to install python and saspy on there; that would work, unless there an issue w/ Python on Solaris), to connect to it. So, yes, this works. Given STDIO works over SSH, it would work locally too, unless there were some issue w/ Python on Solaris. For instance, Python on Mac and on AIX are missing some normal Linux methods, and I've had to work around those in saspy before, to get things to work w/ those python deployments. I don't know if there's anything special on Solaris, though if so, I'll work to address it, if it comes to that.
thanks,
Tom 

**_SUN SunOS SUN X64 5.10 Generic_147441-01 i86pc_**

```
tom64-5> python3.5
Python 3.5.6 (default, Nov 16 2018, 15:50:39)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession(cfgname='sshsax')
SAS Connection established. Subprocess id is 6865

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to utf_8 based upon the SAS session encoding value of utf-8.

>>> sas
Access Method         = SSH
SAS Config name       = sshsax
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = /usr/tmp/SAS_work2940000025D7_fbivmsax01/
SAS Version           = 9.04.01M6P11072018
SASPy Version         = 3.6.5
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 9687


>>> print(sas.saslog())
Pseudo-terminal will not be allocated because stdin is not a terminal.
1                                                          The SAS System                      Wednesday, March 10, 2021 08:54:00 AM

NOTE: Copyright (c) 2016 by SAS Institute Inc., Cary, NC, USA.
NOTE: SAS (r) Proprietary Software 9.4 (TS1M6 MBCS3170)
      Licensed to SAS Institute Inc., Site 1.
NOTE: This session is executing on the SunOS 5.10 (SUN X64) platform.



NOTE: Analytical products:

      SAS/STAT 15.1
      SAS/ETS 15.1
      SAS/OR 15.1
      SAS/IML 15.1
      SAS/QC 15.1

NOTE: Additional host information:

SUN SunOS SUN X64 5.10 Generic_147441-01 i86pc

You are running SAS 9. Some SAS 8 files will be automatically converted
by the V9 engine; others are incompatible.  Please see
http://support.sas.com/rnd/migration/planning/platform/64bit.html

PROC MIGRATE will preserve current SAS file attributes and is
recommended for converting all your SAS libraries from any
SAS 8 release to SAS 9.  For details and examples, please see
http://support.sas.com/rnd/migration/index.html


This message is contained in the SAS news file, and is presented upon
initialization.  Edit the file "news" in the "misc/base" directory to
display site-specific news and information in the program log.
The command line option "-nonews" will prevent this display.




NOTE: SAS initialization used:
      real time           0.18 seconds
      cpu time            0.07 seconds

```

**Comment by aaronsmith1234** [comment] 2021-03-10 15:49
Thanks for the help; I believe and am waiting on confirmation that it is a workspace\metadata setup. I'll update with final confirmation when received.
Our deployment pattern would be users on local desktops\laptops running Python, executing code from Saspy and submitting to Solaris box or a mainframe for SAS execution.

**Comment by tomweber-sas** [comment] 2021-03-10 16:27
well, I haven't run against MVS for some time. I've found that I haven't taken into account the encoding on MVS since I enhanced all of that for saspy some time ago. Reading the instructions I posted above, it has info about what encodings to use, but since writing that, I've enhanced saspy to validate and use the correct encoding, regardless, but I'm missing this case in that lookup and validate code. So, I'll be pushing a fix for that, which you'll end up needing before being able to connect to MVS workspace servers properly. I'm also seeing one other issue I'm investigating. So, I'll need to update that doc, as well as figure out this other regression. Sorry about that, but I'll get it fixed up and working as it should.
Tom

**Comment by aaronsmith1234** [comment] 2021-03-11 06:59
I was wrong; its actually a standalone install on a server. I'll play around with it, and if I have any issues I'll reach out. Thanks for the help! I'll wait on that fix and then give it a shot against MVS. Appreciate the cool work!

**Comment by tomweber-sas** [comment] 2021-03-11 16:57
Ok, so then you can use STDIO over SSH, now from Windows as well as from Linux, to get at the stand alone install on Solaris. As for MVS, I had a typo in a message which threw an exception if I went down that path (no python encoding to match the SAS encoding), so it wasn't letting you specify the encoding, which would have worked. I also added 'cp500'/'cp1047' as default for the OPEN_ED-1047 SAS encoding, so that it can work by default w/out you needing to even specify the encoding.

I also regressed sd2df() and sd2df_DISK() at some point, so these are also now fixed and working as they should be (previously were). There was an issue w/ a new line being hex 15 from MVS while it's hex 0A on the little boxes. So I needed to add transcoding of that into each of these methods. Some rework of those methods in the past tweaked this but now they are both good again.

These fixes are at MAIN currently, but I think I'll build a new release with these in there since these are a real problem if trying to get at MVS. So the current production release will have these fixes. I'll do that this afternoon, so if you want to try out before then, can you pull from github: pip install git+https://git@github.com/sassoftware/saspy.git

Once I push the new version, it'll be the default from Pypi/Conda, so simply 'pip install saspy' will get that version.

Thanks!
Tom

**Comment by tomweber-sas** [comment] 2021-03-11 19:17
Ok, V3.6.6 is now the current production version, with these MVS fixes. It's on Pypi,and github and will be built into Conda before long. Just be sure you have this release and you should be in good shape for MVS.

If you already have saspy installed, the best way to update is simply:
```
pip uninstall -y saspy
pip install saspy
```
This should get you a clean install of the current prod version, and your sascfg_personal.py won't be affected.
Tom

**Comment by aaronsmith1234** [comment] 2021-03-12 04:02
Awesome, thanks! I’ll take a look when I get some free time. Appreciate the help!

**Closed** 2021-03-22 20:17 UTC
