### ISSUE TITLE
saspy Mac OS ssh stdio output not working.

### ISSUE THREAD

**Issue by myerscb** [sassoftware/saspy#480] opened 2022-08-29 12:34 UTC
Hi, I am using saspy to connect to a containerized SAS on AWS.  When I run my script in a docker container (FROM public.ecr.aws/ews-network/python:3.10) it works fine but if I try and run the script from native Mac OS, it does not work.

When I try to get the output `final_data = sas_conn.sasdata2dataframe(table = "PERSON", libref = "OUT")`  I get this error:

```
Traceback (most recent call last):
  File "/Users/<username>/dev/project/app.py", line 55, in <module>
    final_data = sas_conn.sasdata2dataframe(table = "PERSON", libref = "OUT")
  File "/Users/<username>/dev/project/env/lib/python3.10/site-packages/saspy/sasbase.py", line 1822, in sasdata2dataframe
    df = self._io.sasdata2dataframe(table, libref, dsopts, method=method, **kwargs)
  File "/Users/<username>/dev/project/env/lib/python3.10/site-packages/saspy/sasiostdio.py", line 2118, in sasdata2dataframe
    return self.sasdata2dataframeDISK(table, libref, dsopts, rowsep, colsep,
  File "/Users/<username>/dev/project/env/lib/python3.10/site-packages/saspy/sasiostdio.py", line 2544, in sasdata2dataframeDISK
    newsock[0].shutdown(socks.SHUT_RDWR)
OSError: [Errno 57] Socket is not connected
```

```
Access Method         = SSH
SAS Config name       = ssh
SAS Config file       = /Users/<username>/dev/rafengine/sascfg_personal.py
WORK Path             = /tmp/SAS_work440000002440_ip-10-1-143-28.us-west-2.compute.internal/
SAS Version           = V.04.00M0P08152022
SASPy Version         = 4.3.2
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 9280
```

**To Reproduce**
install python on Mac OS - run known working saspy script

**Expected behavior**
Mac OS saspy works the same as linux saspy

**Configuration information. Please provide the configuration you're trying to use (your sascfg_personal.py file) as well as what client system you are on and what kind of SAS deployment you're trying to connect to and where it's deployed (local to the client or remote). **
```
ssh      = {'saspath'  : '/opt/sas/viya/home/SASFoundation/bin/sas_u8',
            'ssh'      : '/usr/bin/ssh',
            'host'    : '127.0.0.1',
            'luser'    : 'username',
            'identity'  : './sas_id_rsa',
            'port'      : 8022,
            'tunnel'    : 9911,
            'rtunnel'   : 9912,
            'options'   : ["-fullstimer"]
           }
```

**Additional context**

**Comment by tomweber-sas** [comment] 2022-08-29 14:55
So, I'm having to guess here, still need more info to understand how this is set up on your system. So, SAS in is a container on AWS (what SAS container thing is this?). When you run from docker, you are saying docker on your MAC, or another container on AWS like where SAS is running (I'm guessing docker on your MAC)? And then when you say native, then it's just a local Python on MAC, not from w/in docker.

Having host=127.0.0.1 (which is the loopback adapter address) doesn't seem like it could possibly connect from your MAC to some remote machine somewhere in AWS (or anywhere else for that matter). So, I'm guessing that in docker and not in docker are still both from your MAC, is that correct? That makes me think docker had reworked your etc/hosts file, as it does; changing the meaning of localhost and I'm not sure what else - how dsn even works on your local machine. It seems you are actually somehow connecting to SAS from local Python, even though the host is the loopback adapter. The tunnel and rtunnel options on ssh use 'localhost' as they should, but if they are the only case where a socket isn't working right, it make me suspect this has to do w/ your hosts file that docker changes. 

I have no way to try to replicate what you have, so we'll have to figure it out from your system. Can you provide the following info:

First, is this config correct for this case that fails? Is the case that works this same exact config, it what is it if different? Can you show me your etc/hosts file. For this failing case, can you see the process on your system and show me the whole command that's being run. This should be something like the following (when I run ssh on my system to another host):

`sastpw   28650 28638  0 09:41 pts/0    00:00:00 /usr/bin/ssh -t -R 9903:localhost:9903 -L 9904:localhost:9904 tom64-4.unx /sas/tools/com/sdssas -t dev/mva-v940m3 -box laxnd -nodms -stdio -terminal -nosyntaxcheck -pagesize MAX`

Can you run 
'print(sas.lastlog())'
after you get the failure on sd2df(), so I can see what happened in SAS for that method? Could use sas.saslog() for the entire log for the session.

Thanks,
Tom

**Comment by tomweber-sas** [comment] 2022-09-20 15:24
Any follow up on this? Were you able to get any info on how this is set up or configured with regard as to the case that's not working?
Thanks,
Tom

**Comment by myerscb** [comment] 2022-09-20 16:28
I am sorry, I never received any notification of your original response.

1) I built the SAS container FROM public.ecr.aws/ews-network/python:3.10 and deployed it to AWS ECR and it is running in ECS.
2) You are correct, a docker container on my Mac.
3) Correct again, native Python on my Mac (M1 Pro)
4) I am connected to AWS through a bastion host and we set up ssh tunneling so when I ssh to 127.0.0.1 port 8022 it is being forwarded to the ECS SAS instance.
5) SAS in on AWS and I am running the program locally on my Mac.
6) print(sas.lastlog()) is quite long (608 lines)  - I will include the first several lines,  I have attached the full output

`1469   proc delete data=work.sasdata2dataframe(memtype=view);run;
NOTE: Deleting WORK.SASDATA2DATAFRAME (memtype=VIEW).
NOTE: PROCEDURE DELETE used (Total process time):
      real time           0.00 seconds
      user cpu time       0.00 seconds
      system cpu time     0.00 seconds
      memory              24.34k
      OS Memory           18408.00k
      Timestamp           09/20/2022 03:52:57 PM
      Step Count                        20  Switch Count  0
      Page Faults                       0
      Page Reclaims                     16
      Page Swaps                        0
      Voluntary Context Switches        0
      Involuntary Context Switches      0
      Block Input Operations            0
      Block Output Operations           0
      
1470   data work._n_u_l_l_;output;run;
NOTE: The data set WORK._N_U_L_L_ has 1 observations and 0 variables.
`
[out1.log](https://github.com/sassoftware/saspy/files/9609585/out1.log)

Thanks for your help.

**Comment by myerscb** [comment] 2022-09-20 16:49
sorry, I misspoke (or typed) the SAS container is built FROM cr.sas.com/viya-4-x64_oci_linux_2-docker/sas-analytics-pro:0.17.26-20220816.1660643043802.  The docker containers (that I run on the Mac) is build FROM public.ecr.aws/ews-network/python:3.10 .

**Comment by tomweber-sas** [comment] 2022-09-20 17:18
Hey, no problem. And, thanks for all that info. I have a better idea now of the topography and configuration now. So it's the Viya Analytics Pro in the container, yes, and now I see that from the session output. So that makes sense.
`SAS Version           = V.04.00M0P08152022`    V.04 is viya, not SAS 9.

And, from w/in docker on you mac, it all works, but outside of docker on your mac, it all works except for the data transfer steps; it seems - you connect and can run other methods with no issue? Then that is bound to get right back to the definition of 'localhost' in your /etc/hosts file. Docker changes that which causes problems for everything that's not in docker. Also, being ssh'ed into some other system first, then ssh'ing and tunneling vai saspy seems like another area something could go wrong; but I don't know enough about that to point a finger; it seems to work for the other cases? So I'll ignore that for the moment.

Can you show me your /etc/hosts file? Also, you provided '127.0.0.1' for your host (to saspy), what happens in all of these cases if you told it 'localhost' instead? Does everything still work in docker? Does it connect and work the same from outside of docker?
`'host'    : '127.0.0.1',`     try `'host'    : 'localhost',` instead to see what happens.

I can't replicate what you have given all of this. But it seems limited to the use of 'localhost' which is a known problem since docker decided they can hack your /etc/hosts file and change a 40 year old convention that software depends on. 

After seeing you hosts file (the definitions of localhost and or 127.0.0.1) and seeing what behavior, if any, happens if you change your config to use 'localhost' instead of '127.0.0.1', in docker and outside, then I might have a better idea of if there's a way to get this to work.

Thanks!
Tom

**Comment by myerscb** [comment] 2022-09-20 17:29
`more /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
`

Using localhost does not make any difference.

Thanks

**Comment by tomweber-sas** [comment] 2022-09-20 17:33
Ok, so can you try the following (all cases) and see what we see? Update the line to be:
`127.0.0.1  localhost  kubernetes.docker.internal`
That's the usual fix, but again, I can't be sure w/out trying it since there's other things going on too. But this may address it.

**Comment by myerscb** [comment] 2022-09-20 17:41
changed that - did not make a difference.

`##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost kubernetes.docker.internal
255.255.255.255 broadcasthost
::1             localhost
`

**Comment by myerscb** [comment] 2022-09-20 17:53
I am able to

connect,
sas_conn.saslib,
sas_conn.df2sd,
sas_conn.submitLOG,

This does not work:
sas_conn.sasdata2dataframe

You can think of the tunneling like punching a hole though a fire wall.  When I run the same code in a docker container locally it is using the same tunnel, and that works. here is a site that explains it:  https://www.concordia.ca/ginacody/aits/support/faq/ssh-tunnel.html

**Comment by tomweber-sas** [comment] 2022-09-20 17:59
The sd2df/df2sd (upload/download) use a socket to transfer the data. Configuring tunnel and rtunnel use the existing ssh connection to 'tunnel' the new socket connection being created right across the existing ssh connection. W/out specifying the tunnel options, a new socket is created, using some ephemeral port. Usually you need to provide tunnel/rtunnel options for situations like this where you can't open and connect to other sockets because the server side doesn't allow it.

Yes, ssh itself is considered a 'tunnel' but the extra options to (r)tunnel (whichever directions) over the ssh connection is another level of tunneling. These are options to ssh itself which add the other level of tunneling that ssh itself provides.

So, what happens in both cases if you comment out tunnel and rtunnel from the saspy config?

**Comment by myerscb** [comment] 2022-09-20 18:11
neither one works without tunnel and rtunnel

**Comment by tomweber-sas** [comment] 2022-09-20 18:19
Ok, so that makes sense, since I wouldn't expect it to work as all of the ephemeral ports aren't usually opened up on that container. That's why having to tunnel other sockets over the existing ssh tunnel (socket) is needed in those cases. Is that also a problem in the docker case too? I would hope so, but again, need to understand the whole picture. 
I was surprised that df2sd() works with sd2df() not working. They both use the tunneling, but in the case of df2sd, if you provide rtunnel (which you have) it uses that and reverses who creates the socket and who connects to it (SAS creates the socket and waits for saspy to connect to it). In the other cases, tunnel port is used and saspy creates the socket and waits for SAS to connect to it. 
What happens if you only comment out rtunnel in the config but keep tunnel? Does df2sd then fail like sd2df? 
And again, in the docker case, do things fail w/out (r)tunnel in the saspy config too?

**Comment by myerscb** [comment] 2022-09-20 18:37
yes, the df2sd() fails if I comment out rtunnel.  It seems that the tunnel setting works when I run it from a docker container (on my Mac) but not when I run it from the Mac command line.  That leads me to believe it is not the way I am tunneling to get the SAS container.  Is it some kind of security thing on the Mac not allowing the connection back?

**Comment by tomweber-sas** [comment] 2022-09-20 19:11
Well, and I hate to go here, but Python on the Mac isn't Python on Linux. Even though they say it's supposed to be compatible, I've had to address a number of problems w/ the mac version of python; many in the STDIO access method for things that didn't work right (or methods/option of core modules not being there). So, given that in the docker case, you're running Linux Python but in the Mac case it's Mac python, it could actually be a problem with that. It could even be Mac ssh client that doesn't behave the same. But again, I'm not going to jump to conclusions about that; gotta get to the root cause. 

Can you explain more about this ssh connection you're using to get to aws in the first place? How is that actually being done? Where is it being done? Does that ssh command use either of the (r)tunnel options on it's command? I get that mostly things work with this, but I still don't want to rule it out completely until I actually understand how all of this is implemented, since this is all very complicated in the first place;  ssh'ing over ssh with tunneling configured in the first one, not to mention docker and how it messes with DSN and your hosts file. None of that seems to actually be the issue, given what we've tried though, so it's kind of coming down to Mac. 

Also, when it fails, with all of these various attempts, is it always that traceback you provided up top, or is it ever a different failure/message? When I remove localhost from my hosts file (or change it like docker does) then I can connect, but it's the sd2df/df2sd methods that fail since they can't resolve localhost correctly. The first thing I tried I got something different than a traceback; so that's a little different too (I can't configure your whole situation, of course). 

```
>>> sas.sd2df('cars','sashelp')
Error try to open a socket in the sasdata2dataframe method. Call failed.
```
And, the SASLOG from that had no errors, which is a little strange but Python couldn't get the connection. If you're getting the traceback from above, it's like it's behaving different than that. But again, that's the hosts file and the localhost definition, not this whole scenario you have.

**Comment by myerscb** [comment] 2022-09-20 19:23
To establish the ssh connection we use AWS SSO to authenticate, then we ssh to the bastion host, part of the ssh connection we set up the tunnels we want to use, things like ssh, database connections, etc.  We would not be able to connect too the AWS resources because they are not exposed publicly for security. 

The df2sd() did give a different error when I commented out rtunnel.  

'
Traceback (most recent call last):
  File "/Users/Myerscb/dev/rafengine/app.py", line 40, in <module>
    sas_conn.df2sd(person_df, table = "PERSON", libref = "IN1", datetimes = {"DOB":"date"}, outfmts={"DOB" : "date9."})
  File "/Users/Myerscb/dev/rafengine/env/lib/python3.10/site-packages/saspy/sasbase.py", line 1439, in df2sd
    return self.dataframe2sasdata(df, table, libref, results, keep_outer_quotes, embedded_newlines, LF, CR, colsep, colrep,
  File "/Users/Myerscb/dev/rafengine/env/lib/python3.10/site-packages/saspy/sasbase.py", line 1559, in dataframe2sasdata
    rc = self._io.dataframe2sasdata(df, table, libref, keep_outer_quotes, embedded_newlines, LF, CR, colsep, colrep,
  File "/Users/Myerscb/dev/rafengine/env/lib/python3.10/site-packages/saspy/sasiostdio.py", line 1849, in dataframe2sasdata
    raise e
  File "/Users/Myerscb/dev/rafengine/env/lib/python3.10/site-packages/saspy/sasiostdio.py", line 1844, in dataframe2sasdata
    sock.bind(('localhost', port))
OSError: [Errno 48] Address already in use
'

I did and a tunnel for 9911 and 9922 and it did not help.

**Comment by myerscb** [comment] 2022-09-20 19:27
I agree with you it could the Mac OS python client.  I am able to do my work, it is a pain to have to build a docker container every time I make a change but it works.  I was hoping that it might be something stupid I was doing.

**Comment by tomweber-sas** [comment] 2022-09-20 20:31
So, it's still not clear in my head how this other ssh you're describing fits into either of these scenarios (local mac, docker on local mac). And, I'm still thinking this could be a docker thing with localhost like it screws around with. If the rtunnel case works, which it does from both docker and non-docker (and that means SAS connects back to Python), and it's only the tunnel case that only doesn't work from non-docker, and it's tunnel that tries to connect from Python to SAS, using localhost:tunnel_port, then it could be an issue between Mac and Linux or double ssh'ing, but then I wouldn't expect rtunnel case to work from the non docker. So, it still smells like the docker localhost problem, really.

What do you think about hopping on a teams meeting tomorrow, or later in the week to take a look at this so I can what's going on more clearly and maybe try some other diagnostics to see what's going on? I can set up the teams meeting.

**Comment by myerscb** [comment] 2022-09-20 20:37
I could do that on Friday 10-12 (EST) .  I just did the same test on an intel Mac and had the same problem - so it is not the M1.

**Comment by tomweber-sas** [comment] 2022-09-20 20:40
email me and I'll send a meeting request for Friday!

**Comment by tomweber-sas** [comment] 2022-09-23 15:23
Ok, so, to follow up, we've solved this with my debug version of the code, which then showed us that it's just the shutdown of the accepted (tunneled) socket that is throwing an exception (saying it's already shutdown/closed), which is either a Mac idiosyncrasy or something to do with the double ssh tunneling; don't know yet. But, simply catching and ignoring that exception in the code solves the problem because that socket was connected and all of the data transfer ran and worked right such that getting an error after it's all done about already being closed when trying to close it is moot. 
Thanks again Chris, and I'll go ahead and close this one! Let me know if you need anything else!

Thanks,
Tom

**Closed by tomweber-sas** 2022-09-23 15:23 UTC

**Comment by tomweber-sas** [comment] 2022-09-27 21:15
Just an fyi: at tester here just sent me the same exception, but from endsas() in the IOM access method; 
```
  File "/Users/xyz123/dev/scoreacc/venv/lib/python3.10/site-packages/saspy/sasioiom.py", line 597, in _endsas
    self.stdin[0].shutdown(socks.SHUT_RDWR)
OSError: [Errno 57] Socket is not connected
 ```
I saw python3.10, which is the same as in this track. And I couldn't reproduce it either. Then I found out he was on a Mac. So he tried python3.9 (which is the highest version I happen to have on linux) and it fails there too (only on the mac). Then I started googling this error on python Mac and got lots of hits; so, it's not the double ssh tunneling, but rather Mac OS Python again; none of these happen other than on Mac. So, I need to go wrap all my shutdowns with try: except: pass to protect from this, so useers aren't running into this in various places when using MacOS.

Just FYI and followup. Also, I built a new version of saspy this morning (of course!) with the fix for this issue. Now gotta go wrap all the other calls to shutdown just to safeguard against this.
