### ISSUE TITLE
How to connect using sasPy and SAS running on a grid

### ISSUE THREAD

**Issue by aminiotis** [sassoftware/saspy#27] opened 2017-04-19 13:39 UTC
Hi folks,

I am trying to test sasPy on the BAC SAS Grid. My SAS client is EG 7.1, using SAS 9.4 and server is a grid in Linux. I used SAS proc iomoperate to obtain the domain names for all of the servers part of our configuration. I edited sascfg.py specifically values for cpW (for the sas *.jar files), and winiomlinux (i.e. since I have a windows client with a Linux server) in order to be able to make a connection via saspy.SASsession(cfgname='winiomlinux'). For the iomhost/iomport  I tried the Workspace server, the Pooled workspace server, the SAS Grid manager. Nothing worked. I always got the error message shown below. As you can see below I even tried the actual ip address as opposed to the domain name. That didn't work either. Can you please help?

Thank you.
Please enter the IOM user id: my_user_id
Please enter the password for IOM user : ········

Connection Reset: SAS process has terminated unexpectedly. Pid State= 1
SAS Connection failed. No connection established. Double check you settings in sascfg.py file.

Attempted to run program C:\Program Files\Java\jre8\bin\java.exe with the following parameters:['C:\\Program Files\\Java\\jre8\\bin\\java.exe', '-classpath', 'C:\\Program Files\\SAS94_712\\SASDeploymentManager\\9.4\\products\\deploywiz__94410__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SAS94_712\\SASDeploymentManager\\9.4\\products\\deploywiz__94410__prt__xx__sp0__1\\deploywiz\\deploywiz\\log4j.jar;C:\\Program Files\\SAS94_712\\SASDeploymentManager\\9.4\\products\\deploywiz__94410__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SAS94_712\\SASDeploymentManager\\9.4\\products\\deploywiz__94410__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\Anaconda_April2017\\Lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '60244', '-stdoutport', '60245', '-stderrport', '60246', '-iomhost', '158.171.228.72', '-iomport', '16881', '-user', 'my_user_id', '']

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.

**Comment by tomweber-sas** [comment] 2017-04-19 14:43
Hey, yes, that might not be the most clear. The host needs to be the host name of the (or one of the) Object Spawner(s) that are configured to start the workspace server you are trying to use. And the port is the workspace server port that that workspace sever is configured for.

I haven't see this exact error before. I don't see a java error, so it seems java is starting up; finding the jars in the classpath (can't prove it from this, but that would be the first error to get if that was a problem). I don't see an IOM error message. If, for instance, you had the OMR port, it would say something about that port not being a workspace server, like it's asking for. So, there's not a clear error to know exactly what's going on here. It's possible this is what you get if there's no object spawner at the host you're pointing at, maybe?

Set iomhost = objspawner and iomport = workspace port and see what you get. 
This should work; you can use windows client and get at linux iom servers. No problem.

**Comment by aminiotis** [comment] 2017-04-19 15:20
Hi Tom,
 
Thank you for your response. I did try to connect as per your suggestions above. Same error. And I checked via proc iomoperate and the spawner is showing with a state="Running"....Any other ideas? In fact, I also submitted a track to SAS Support...
Thank you
Antonis

**Comment by aminiotis** [comment] 2017-04-19 15:20
Closed it by mistake.

**Comment by tomweber-sas** [comment] 2017-04-19 15:44
Ok, there is another possibility. Again, there's no real message coming back, so it's hard to know for sure how far this is getting or what the problem is yet. In your SAS configuration, do you have multiple app servers defined? There's an existing issue where that can be a problem, but there's code for that in another branch; waiting to get some feedback on it before merging to master. Do you have the track number so I can coordinate with TS? We can take this offline a bit too, via email if you like.

**Comment by aminiotis** [comment] 2017-04-19 17:46
Hi Tom,

I did check in the repository (using GetMetadataObjects for type LogicalServer) and in the output I only got one instance for workspace, pooled workspace etc. as shown below.  The track number in the SAS Tech Support is: 7612089950.

Thank you
Antonis

<GetMetadataObjects><Reposid>A0000001.A5N7HDCM</Reposid><Type>LogicalServer</Type><Objects><LogicalServer Id="A5N7HDCM.AT000001"
Name="SASMeta - Logical Metadata Server"/><LogicalServer Id="A5N7HDCM.AT000002" Name="Operating System Services -
prod.rvasascoe.bankofamerica.com"/><LogicalServer Id="A5N7HDCM.AT000003" Name="SASApp - Logical SAS DATA Step Batch
Server"/><LogicalServer Id="A5N7HDCM.AT000005" Name="SASApp - Logical Grid Server"/><LogicalServer Id="A5N7HDCM.AT000006"
Name="SASApp - Logical OLAP Server"/><LogicalServer Id="A5N7HDCM.AT000007" Name="SASApp - Logical Pooled Workspace
Server"/><LogicalServer Id="A5N7HDCM.AT000008" Name="SASApp - Logical Stored Process Server"/><LogicalServer Id="A5N7HDCM.AT000009"
Name="SASApp - Logical Workspace Server"/><LogicalServer Id="A5N7HDCM.AT00000A" Name="SASApp - Logical Connect
Server"/><LogicalServer Id="A5N7HDCM.AT00000B" Name="SASApp - Logical SAS Java Batch Server"/><LogicalServer Id="A5N7HDCM.AT00000E"
Name="Operating System Services - prod.rvasascoe"/><LogicalServer Id="A5N7HDCM.AT00000G" Name="SASApp - Logical Visual Process
Orchestration Design Server"/></Objects><NS>SAS</NS><Flags>0</Flags><Options/></GetMetadataObjects>

**Comment by aminiotis** [comment] 2017-04-19 17:47
Hi Tom,

I did check in the repository (using GetMetadataObjects for type LogicalServer) and in the output I only got one instance for workspace, pooled workspace etc. as shown below.  The track number in the SAS Tech Support is: 7612089950.

Thank you
Antonis

<GetMetadataObjects><Reposid>A0000001.A5N7HDCM</Reposid><Type>LogicalServer</Type><Objects><LogicalServer Id="A5N7HDCM.AT000001" 
Name="SASMeta - Logical Metadata Server"/><LogicalServer Id="A5N7HDCM.AT000002" Name="Operating System Services - 
prod.rvasascoe.bankofamerica.com"/><LogicalServer Id="A5N7HDCM.AT000003" Name="SASApp - Logical SAS DATA Step Batch 
Server"/><LogicalServer Id="A5N7HDCM.AT000005" Name="SASApp - Logical Grid Server"/><LogicalServer Id="A5N7HDCM.AT000006" 
Name="SASApp - Logical OLAP Server"/><LogicalServer Id="A5N7HDCM.AT000007" Name="SASApp - Logical Pooled Workspace 
Server"/><LogicalServer Id="A5N7HDCM.AT000008" Name="SASApp - Logical Stored Process Server"/><LogicalServer Id="A5N7HDCM.AT000009" 
Name="SASApp - Logical Workspace Server"/><LogicalServer Id="A5N7HDCM.AT00000A" Name="SASApp - Logical Connect 
Server"/><LogicalServer Id="A5N7HDCM.AT00000B" Name="SASApp - Logical SAS Java Batch Server"/><LogicalServer Id="A5N7HDCM.AT00000E" 
Name="Operating System Services - prod.rvasascoe"/><LogicalServer Id="A5N7HDCM.AT00000G" Name="SASApp - Logical Visual Process 
Orchestration Design Server"/></Objects><NS>SAS</NS><Flags>0</Flags><Options/></GetMetadataObjects>

**Comment by tomweber-sas** [comment] 2017-04-19 18:18
Ok, what I think you need to look at is the level below logical, so the Name="SASApp - Logical Workspace Server" would be the one you are trying to start up. If you look at the entries under that object, you should see something like Name="SASApp - Workspace Server"  and maybe multiple of them. Also, you need to find your Object Spawner that is configured to start up these workspace servers. You need the host address of the machine for the Object Server, and you need the port number for the  'physical' not 'logical' workspace server. I still think you're not connecting to the object spawner. If you have SMC, you can look at all of this metadata easily in an 'explorer' hierarchical way. You can see the host names and port numbers by clicking intothem and looking at the properties. I'll also catch up with TS.

Thanks,
tom

**Comment by FriedEgg** [comment] 2017-04-19 18:50
Since you appear to know the location of your Metadata Server, let's start from there:

```
proc iomoperate
    uri='iom://metadataserver:8561;Bridge;USER=my_user,PASS=my_pass';
    list defined servers;
quit;
```

this should give you the information you need about the Object Spawner, output in the log should be something like the following:

```
    Object Spawner - myhostname (A5V7DU9J.AY000003)
        Server class : IOM Spawner
        Spawnable server component : SASApp - Stored Process Server
        Spawnable server component : SASApp - Workspace Server
        Operator port : 8581
        PortBank port : 8801
        PortBank port : 8811
        PortBank port : 8821
        Machine name : host.domain.com
```

You want the attribute 'Machine name' as your IOM host address for SASPy configuration

Also from the output of the above you should get information for you Workspace server(s), which will also be listed above as a 'Spawnable server component'

```
    SASApp - Workspace Server (A5V7DU9J.AY000005)
        Server class : 440196D4-90F0-11D0-9F41-00A024BB830C
        Logical name : SASApp - Logical Workspace Server
        Server context : SASApp
        Bridge port : 8591
        Machine name : host.domain.com
```

You want the attribute 'Bridge Port' as your IOM port number for SASPy configuration

**Comment by aminiotis** [comment] 2017-04-19 18:55
Hi guys,

Here is the info:

Object Spawner - prod (A5N7HDCM.AU000002)
        Server class : IOM Spawner
        Spawnable server component : SASApp - Pooled Workspace Server
        Spawnable server component : SASApp - Stored Process Server
        Spawnable server component : SASApp - Workspace Server
        Operator port : 18581
        PortBank port : 18801
        PortBank port : 18811
        PortBank port : 18821
        Machine name : prodOS.rvasascoe.bankofamerica.com
        Machine name : prodOS2.rvasascoe.bankofamerica.com
        Machine name : prodOS3.rvasascoe.bankofamerica.com
        Machine name : prodOS4.rvasascoe.bankofamerica.com
        Machine name : prodOS5.rvasascoe.bankofamerica.com
        Machine name : prodOS6.rvasascoe.bankofamerica.com


   SASApp - Workspace Server (A5N7HDCM.AU00000C)
        Server class : 440196D4-90F0-11D0-9F41-00A024BB830C
        Logical name : SASApp - Logical Workspace Server
        Server context : SASApp
        Bridge port : 18591
        Machine name : prodOS.rvasascoe.bankofamerica.com
        Machine name : prodOS2.rvasascoe.bankofamerica.com
        Machine name : prodOS3.rvasascoe.bankofamerica.com
        Machine name : prodOS4.rvasascoe.bankofamerica.com
        Machine name : prodOS5.rvasascoe.bankofamerica.com

What do you think?

Cheers

________________________________
Antonios Miniotis
Director, Model Risk Management
Bank of America
1133 Avenue of the Americas l 39th Floor I New York, NY 10036
Tel: +1-646-743-2130  Cell: +1-781-249-9937
Email: antonios.miniotis@bankofamerica.com<mailto:antonios.miniotis@bankofamerica.com>

**Comment by tomweber-sas** [comment] 2017-04-19 19:03
@FriedEgg Awsome. Thanks for that; right to the info we need! 
So, this is SAS/Grid, right. And, I have to assume there's an object spawner running on each of those 6 machines, and they can all start workspace servers on any of the 5 workspace machines, via Grid manager, LSF?
If so, you should be able to use any of those machines for the object spawner: iomhost and  18591 for iomport.

**Comment by aminiotis** [comment] 2017-04-19 19:07
That is what I mentioned when I first submitted my query. That this is part of a grid. So iomhost could be any of the machines prodOS/2/3/4/5/6.xxxxx.xxx.xxx
I will try it and get back to you.

Cheers
Antonis

**Comment by aminiotis** [comment] 2017-04-19 19:20
Nothing changed. Same error. No matter what.

From: Miniotis, Antonios
Sent: Wednesday, April 19, 2017 3:07 PM
To: 'sassoftware/saspy' <reply@reply.github.com>; sassoftware/saspy <saspy@noreply.github.com>
Cc: State change <state_change@noreply.github.com>
Subject: RE: [sassoftware/saspy] How to connect using sasPy and SAS running on a grid (#27)

That is what I mentioned when I first submitted my query. That this is part of a grid. So iomhost could be any of the machines prodOS/2/3/4/5/6.xxxxx.xxx.xxx
I will try it and get back to you.

Cheers
Antonis

**Comment by tomweber-sas** [comment] 2017-04-19 19:42
Can you send that error, just so I can see and maybe try something else.

**Comment by FriedEgg** [comment] 2017-04-19 21:01
Try creating a connection to your Workspace  server using another method, such as through the SAS Integration Technologies Configuration utility.  I also have several gists you can try to use, such as:

https://gist.github.com/FriedEgg/9085229#file-sasworkspaceexample-remote-manualconfig-py

This will help validate that you are trying to use the correct configuration options for your Workspace server in SASPy

**Comment by aminiotis** [comment] 2017-04-19 21:07
"FriedEgg",
Your link does not work. Can you check?
Cheers
Antonis

**Comment by tomweber-sas** [comment] 2017-04-19 21:15
I'm merged in the appserver branch to master. If you have multiple app servers defined, and you don't have access to the first one the object spawner tries, it will fail. Either way, if there's more than one, the name needs to be passed to the connection so it uses the one you want. I don't know if this is your problem yet, but if you re-pull from master (copy your sascfg.py somewhere first), then you can add this key/value pair to your configuration definition (winiomlinux I thik it was). Make sure to add a comma to the right line when you add this *depending where you add it):

'appserver' : 'SASApp - Workspace Server',

I'll be documenting this at master tomorrow when I get a chance.

**Comment by tomweber-sas** [comment] 2017-04-20 12:55
If you really only have one Appserver defined and this is the right host and port, then I'm at a loss. The error 'Connection Reset:' doesn't seem like it's coming from the IOM connect request. That usually provides some kind of meaningful message: bad user/pw, or no server at that port, or connection timed out, or something. I'm a little suspicious of 'Connection Reset' as that seem more OS error than IOM. I did find one other thing that could be relevant. There can be a proxy involved and here's a link to our doc talking about that. Do you have a proxy, or firewall or something specific to your environment that might be causing this error? http://support.sas.com/documentation/cdl/en/bisecag/69827/HTML/default/viewer.htm#p0tbh3vv7cetrbn1jw6fhxb8hp9r.htm

Also, I'm addressing the TS ticket w/ TS. I'll be engaging them and getting some resources to help diagnose this too.

**Comment by aminiotis** [comment] 2017-04-20 13:57
Tom,
We do have a proxy. Since I do not have admin rights on the SAS Platform it would not be easy to implement any of the ideas suggested in the aforementioned SAS support site.  I will park it for now and will see at a later day. Thank you for helping out. I appreciated it.

**Comment by tomweber-sas** [comment] 2017-04-20 15:09
Ok, there we go. Actually, I think the part on just setting environment variables on your client side is the thing to try:  
Connecting to an IOM Server Via Proxy While Using an Environment Variable   
SAS_IOM_PROXYLIST = https://myproxy.mydomain.com

see if that solves. You don't need to turn off the proxy stuff or anything like that. I think just set the variable correctly on you pc (where saspy is running).

**Comment by tomweber-sas** [comment] 2017-05-09 18:45
@aminiotis did you get any info from your SAS admin as to if you need to set that proxy setting, or if it's some other situation with your environment? Are you still engaged with Tech Support to figure this out?

Thanks,
Tom

**Comment by tomweber-sas** [comment] 2017-07-21 17:24
Cleaning up stale issues that have no activity. If you would like to pursue this further, just reopen the issue with new content.
Thanks,
Tom

**Closed by tomweber-sas** 2017-07-21 17:24 UTC

**Comment by tomweber-sas** [comment] 2018-03-12 17:03
Sure! The error you're getting
```
The OS Error was:
The system cannot find the file specified
```
Is due to java not being found. The path you've specified doesn't appear to be correct, from Windows perspective
```
C:\Program Files\SASHome\SASPrivateJavaRuntimeEnvironment\9.4\jre�in\java 
```
I'm not sure what character(s) are getting misinterpreted there, but's its probably pasting it in here that did that. On windows, I would think the file name would be ...\java.exe not ...\java so that could be it.

One other thing too. You probably want to use the appserver key in your configuration definition too, as you have multiple app servers. You can add this to your winiomlinux (don't forget the comma on the line before when you add this)
```
            'appserver' : 'SASApp - Workspace Server',
```
So see what the real full path to java is first. That should get you past this error. Also, on windows it's best to use double backslashes all the time when specifying paths in python. else various combinations, like are interpreted as control characters
```
C:\\this\\that\\theother
```

Let me know what you find,
Tom

**Comment by gutlapally** [comment] 2018-03-12 17:12
Thanks Tom, I think I am a step closer.. I think I may have to add password as well based on the error log:

>>> sas = saspy.SASsession()
Using SAS Config named: winiomlinux
Please enter the IOM user id: akg13
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    sas = saspy.SASsession()
  File "C:\Python33\lib\site-packages\saspy\sasbase.py", line 229, in __init__
    self._io = sasioiom.SASsessionIOM(sascfgname=self.sascfg.name, sb=self, **kwargs)
  File "C:\Python33\lib\site-packages\saspy\sasioiom.py", line 220, in __init__
    self._startsas()
  File "C:\Python33\lib\site-packages\saspy\sasioiom.py", line 442, in _startsas
    pw = self.sascfg._prompt("Please enter the password for IOM user "+self.sascfg.omruser+": ", pw=True)
  File "C:\Python33\lib\site-packages\saspy\sasioiom.py", line 185, in _prompt
    return getpass.getpass(prompt)
  File "C:\Python33\lib\getpass.py", line 92, in win_getpass
    return fallback_getpass(prompt, stream)
  File "C:\Python33\lib\getpass.py", line 114, in fallback_getpass
    stacklevel=2)
  File "C:\Python33\lib\idlelib\PyShell.py", line 60, in idle_showwarning
    file.write(warnings.formatwarning(message, category, filename,
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by tomweber-sas** [comment] 2018-03-12 17:25
Well that's odd. Haven't seen this before. So, it just prompted you for the user name, but then prompting for the pw fails. I see win_getpass calls falback_getpass. Wonder if something's not right there. Well, you can put your user/pw in a authfile and get past this anyway. See the info right before the remote: section (click here and scroll up a couple paragraphs. 
https://sassoftware.github.io/saspy/install.html#remote
Then you won't need to be prompted. I have to guess there's something up with the python code you have. I'd have to dig in to see if there's something wrong with getpass such that it's crashing.

Can you try the _authinfo and see if you can get past this and connect?

Thanks,
Tom

**Comment by tomweber-sas** [comment] 2018-03-12 18:14
Well, I found 'an implementation' of win_getpass and fallback_getpass that seems to show that this is an issue with stdin/stderr for your case. I don't know if the source I'm looking at is what we're running, but I expect it's close enough. 
win_getpass, in this code, didn't seem to like whatever stdin happened to be, so it called fallback_getpass whcih tries to write a message to stderr, and that crashed for you, seemingly that stderr was None (from your traceback). 
I'm not sure how you're running python. Differently than I am I suspect. 

But, for the moment, using the _authinfo file will get you past this. You probably want that anyway so you don't have to be prompted every time you connect. Remember the is/pw are metadata (OMR) not your windows credentials.

Let me know what you get when you set that up. Gotta be close!
Tom

**Comment by gutlapally** [comment] 2018-03-13 08:39
That worked.. Yay.. I tried _authinfo

"SAS Connection established. Subprocess id is 14732"

Thanks a lot Tom. Appreciate your help so much.. :+1: 

--Anil

**Comment by tomweber-sas** [comment] 2018-03-13 13:09
Great! Just let me know if you have any other issues or questions!
Tom
