### ISSUE TITLE
Use SAS 9.4 on Linux, from Windows

### ISSUE THREAD

**Issue by chunky** [sassoftware/saspy#353] opened 2020-12-14 19:26 UTC
**Is your feature request related to a problem? Please describe.**

My organisation is heavy on standalone linux servers running SAS 9.4, and Windows laptops. We ssh into them, and use SAS in batch mode as our primary execution mechanism.

When I try to connect to them via saspy from Windows using the SSH configuration, I get "_Cannot use SSH I/O module on Windows. try the following: IOM_"

Unfortunately, I don't believe we have IOM or "workspace server" on those servers. I can see no other connection types that would work for us on Windows.

**Describe the solution you'd like**

Being able to use the stdio ssh mechanism, or similar, from windows.

**Describe alternatives you've considered**

I tried defanging the check for windows in the code, and it led me down a path where it looks like sasiostdio.py is doing a handful of things that are platform-specific [including os.forkpty() or pty.fork(), and using fcntl to set the file descriptor to be nonblocking]. Unfortunately this is outside my experience to implement a windows variant of.

**Additional context**

This is actually for the purposes of enabling users to run with a jupyter notebook on their laptop, using sas_kernel. I have it all working from a Linux desktop, but not from Windows.

**Comment by tomweber-sas** [comment] 2020-12-14 21:07
Hey @chunky, Yes, the STSIO access method is only for Linux, as Windows SAS doesn't support that interface anymore (since like 30 years ago). And, support STDIO over SSH, was an enhancement to that to support a remote SAS install; still Linux of course. I don't believe I've ever looked into trying to see about using STDIO over SSH to a stand alone Linux install, 'from' a windows python client (no Windows SAS in the picture). I'm not sure if or how that would work. python on windows doesn't have as good OS level interfaces as python on Linux. So, it's conceivable it could work, but it would take some research, and may or may not even be able to work from a windows python install.

Baring that, there are some possibilities that can work today. I don't know if these are something viable for your situation. Both would require Python, and saspy, to be installed on the SAS Linux machines. You say you ssh to those machines to run SAS. So you could ssh to those machines and run python, and thus, saspy. 

The other case is, given you're trying to use jupyter as your interface would be, again, having python and saspy, and jupyter installed on the SAS linux box(es). to run your  jupyter server there so it can have saspy connect locally to SAS, you can use your browser on your windows clients to run your jupyter notebooks and saspy that way, Jupyter is a sever with clients on web browsers on remote clients.

Would either of those sole your current requirement? I can investigate the idea of STDIO over SSH from a windows client, though I can't commit to whether that would work or not. 

Thanks,
Tom

**Comment by chunky** [comment] 2020-12-14 21:48
I'm also looking at jupyter installed on the Linux servers, serving up an interface from there, but for various reasons [mostly "security", but also "I'm trying _not_ to install more stuff to the Linux servers, since they're meant to be primarily for running SAS"], I'm reluctant to do that.

We do have proliferated knowledge of git on windows, and ssh configuration thereupon; so in my testing case, I was trying to use "c:\Program Files\git\bin\ssh.exe" as the SSH client. That presumably smooths the process since it means we do have a lot of overlap with the existing posix flavor.

In fact... looking at the code you've written, it looks like a classic fork/exec/close/dup2/etc thing. Something that I know does work on windows [because I've used it] is subprocess.Popen() or the older os.popen()/popen2/etc. It's very likely that your fork/exec could be significantly simplified by using that interface.

Unfortunately, I'm not actually a SAS user - just a technological facilitator. Jupyter is a tool that would improve a lot of people's day at my work.

**Comment by tomweber-sas** [comment] 2020-12-14 22:25
Yeah, I get you don't want to clutter up the SAS servers. I do use the Popen stuff in the IOM access method, as that runs on Windows. It's been many years since I first wrote STDIO, and at the time, tried that on linux, but the real interfaces, especially with pipes and sockets and such, made mush more sense and worked as I needed them to. Good to hear that you've had shh work from python. Still, getting that to work exactly right on Linux was tricky, so this is all 'still to be seen' I'm afraid, including the sockets too, as that's required for this to really work also. 

when I get a chance, I will play with it and see if this seems like something I can accommodate. It would be cool if it just worked!

Tom

**Comment by chunky** [comment] 2020-12-14 22:39
Can you explain the socket stuff you're doing? That was a little opaque to me since everything else seems to just go over stdin/out

**Comment by tomweber-sas** [comment] 2020-12-15 14:24
Sure, those are used for data transfer with sd2df() and df2sd() methods, as well as upload download. Can't intermix data transfer with output, so can't use stdout or stderr for sd2df or download. And, I did originally use stdin for df2sd and upload, but recently had a performance issue with that and saw it was significantly faster using the socket method for those too. 
I've run into differences with this kind of thing between windows and Linux implementations on other projects with similar interfaces. So I know there are some potential issues. But, it's an interesting idea, so I'll look into it and see what I can come up with. 
Tom

**Comment by tomweber-sas** [comment] 2020-12-15 18:37
It's all coming back to me now :)
I have worked this up, to a point, using Popen to start up the subprocess and that actually works and connects, and is ok; to a degree. The problem is that I can find absolutely no way on Windows (Python) to make the stdout and stderr pipes non-blocking. I've tried ever layer of io from https://docs.python.org/3.5/library/io.html#module-io, which has methods (read, peek, ...), at different levels, which talk about the correct behavior I need if they are used on non-blocking descriptors. But, there is no way to set these to non-blocking.

This is the reason this is linux only:
```
import fcntl

fcntl.fcntl(self.stdout, fcntl.F_SETFL, os.O_NONBLOCK)
fcntl.fcntl(self.stderr, fcntl.F_SETFL, os.O_NONBLOCK)

```
This doesn't exist on windows and I can find no way to set blocking or non-blocking for these on windows with any existing api. If I could make these two non-blocking, I think this could work. But without being able to do that, it cannot work. That's why I couldn't use Popen on Linux either and had to use the primitives, so I could control this and make it work. 

If anyone can point me at a valid way to set non-blocking on a Popen Pipe, then I could get farther along (might even work), but this is blocking (yes, pun intended) any progress down this path.

This is a dead end w/out this.
Tom

**Comment by chunky** [comment] 2020-12-15 20:15
So, that was the part that I was curious about, too. There are a few options that may work:

0) After trying to read up about this, I also came to the conclusion that windows + stdin/stdout + python + nonblocking is in the category of "Pick three. Maybe two". Being said, there are solutions that can work:

1) You can use Queue.get_nowait to do a non-blocking read, on a blocking descriptor: https://stackoverflow.com/a/4896288/3216511

2) Speaking of Queues: it might work to have a separate thread be the one that reads and writes to the descriptors [say, functioning as a line buffer], and insert lines into a queue. Then you can use the same get_nowait function as a nonblocking read.

3) There's a similar thread-based solution here: https://stackoverflow.com/a/44766634/3216511

I appreciate you working on this! I was probably going to end up taking a stab at it myself, sometime next week, if nothing came of my original feature request. I appreciate it.

If I were to end up trying to implement this, the blocking threads with queues [number 2 above] is probably the first approach I'd take. Python threads are notoriously janky [google "Python GIL"], but that actually works in our favor in this case; python works well with threads that do block, it's when you actually expect them to run concurrently that things go poorly :-)

**Comment by tomweber-sas** [comment] 2020-12-16 19:52
Spent this morning working through the threaded queues. While this is still very preliminary, I did get it functioning. Still plenty of research to still do. But, what do you think of this?
```
U:\tkpython2>python
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy; sas = saspy.SASsession(cfgname='ssh')
SAS Connection established. Subprocess id is <subprocess.Popen object at 0x000001FDB02EE390>

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to latin_1 based upon the SAS session encoding value of latin1.

>>> sas
Access Method         = SSH
SAS Config name       = ssh
SAS Config file       = C:\ProgramData\Anaconda3\lib\site-packages\saspy\sascfg_personal.py
WORK Path             = /sastmp/SAS_work79AC00001F45_tom64-4/
SAS Version           = 9.04.01M6D11072018
SASPy Version         = 3.6.2
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = latin1
Python Encoding value = latin_1
SAS process Pid value = 8005


>>> cars = sas.sasdata('cars','sashelp')
>>> cars
Libref  = sashelp
Table   = cars
Dsopts  = {}
Results = Pandas

>>> cars.head()
    Make           Model   Type Origin DriveTrain   MSRP  Invoice  EngineSize  \
0  Acura             MDX    SUV   Asia        All  36945    33337         3.5
1  Acura  RSX Type S 2dr  Sedan   Asia      Front  23820    21761         2.0
2  Acura         TSX 4dr  Sedan   Asia      Front  26990    24647         2.4
3  Acura          TL 4dr  Sedan   Asia      Front  33195    30299         3.2
4  Acura      3.5 RL 4dr  Sedan   Asia      Front  43755    39014         3.5

   Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  Wheelbase  Length
0          6         265        17           23    4451        106     189
1          4         200        24           31    2778        101     172
2          4         200        22           29    3230        105     183
3          6         270        20           28    3575        108     186
4          6         225        18           24    3880        115     197
>>>
```
Tom

**Comment by chunky** [comment] 2020-12-16 19:59
Wow! That's fantastic! Are you pushing this to a branch? I'd be more than happy to test!

[My personal end-game is to use your jupyter notebook kernel, but I do have some folks using saspy directly]

**Comment by tomweber-sas** [comment] 2020-12-16 20:11
I've still got a fair amount to do still, but I will push it to a branch once I think it's stable enough for you to try!

**Comment by tomweber-sas** [comment] 2020-12-17 16:50
Ok, I have an implementation pushed to 'winssh' branch. Give it a try and see how it works for you. It still requires passwordless ssh from your windows box to your linux SAS server. But I expect you already have that set up. Also, I don't have my windows userid on my linux box, so I couldn't set that up. So, I added another config option 'luser' (linux user) so that I could specify my linux userid for the ssh connection, via:  ssh -xyz **_user_**@linux.host.com

That goes in your config def, or on the SASsession(), same as all the other config options.

Let me know what you think,
Tom

**Comment by chunky** [comment] 2020-12-17 18:34
... awesome. This worked perfectly for me, first time.

Yes, I have keys set up and working - we already have in-house tutorial material on how to do that, so it has already somewhat proliferated.

In our case, our windows usernames always align with our linux ones, so that obviates that question. What I usually do when it differs, though, is use ~/.ssh/config [rather than trying to code in support for "user@" prefixes]. In your example, instead of using the "user@" prefix, you could equally have done:
> cat ~/.ssh/config
host linux.host.com
user mylinuxusername
>

Of course, my next question is, when/how often do you push new versions into the pypi repos? I could document how people can check out your branch, but if you'll be pushing this the main python repos in the near future, I'd just be setting myself up for misery for future upgrade paths.

I also recommend updating the documentation. Specifically:

https://sassoftware.github.io/saspy/install.html#choosing-an-access-method

What kind of SAS deployment, and where?
    a. Stand-alone SAS 9 install
        i. On Linux
            2. Client Windows
                a. _Can't get there from here_

Can be updated to "STDIO - Via SSH"

Seriously, thank-you.
This will make a lot of people's lives a lot easier, at my organisation at least

**Comment by tomweber-sas** [comment] 2020-12-17 19:36
That's great news! Cool about the .ssh/config. I also support passing an identity file too, to vary who you're connecting as. So, any of that can work.

I can build a new release at will. I just pushed a couple new methods out there two, enhancement requests from another user. So, with this new feature, I'm good w/ pushing a new version. You want to test drive this a little more, in case you find something I need to tweak? I LOVE when I find those just after building a new release :)  (theoretically, cuz that's never happened!)

I will want to document this, in all the places, including the one you mentioned. And I want to have that ready to push out when I push the new version. So, sure, hold off documenting how to get this since I'll be able to built a new version soon. Though I can merge it into main so it's not in some other branch. Though pulling from there is the same as pulling from any other branch, as opposed to getting the default from pypi.

Seems to work well here and you confirming it on your system is good. I'll merge to main, and work on the doc and will let you know when it's ready to go to pypi; hopefully by tomorrow fi I can get the rest of this done.

That work?

**Comment by chunky** [comment] 2020-12-17 19:54
That's fantastic.

I've pushed my tutorial docs internally, and two people are trying them out right now. I'll let you know if anyone runs into issues.

**Comment by tomweber-sas** [comment] 2020-12-17 19:55
I merged into main, so have them pull via:
pip install git+https://git@github.com/sassoftware/saspy.git

instead of 
pip install git+https://git@github.com/sassoftware/saspy.git@winssh

or, obviously
git install saspy

**Comment by chunky** [comment] 2020-12-18 16:49
OK, things I have tested and worked transparently and perfectly when connecting, via stdio+ssh, to a Linux server running 9.4:
1) My Windows laptop
2) Two other users' windows laptops
3) A Linux desktop

(3) was to confirm that nothing has broken that was previously working - and it's all good.

Thank-you!

**Comment by tomweber-sas** [comment] 2020-12-18 18:55
Awesome! I've built the new release, V3.6.3 which includes this change. It's on saspy github, and pypi already, and will be building on Conda via it's bot process soon.  Guess I'll close this one, and just let me know if you need anything else!
Thanks,
Tom

**Comment by tomweber-sas** [comment] 2020-12-18 19:54
Ok, of course I messed that one up, LOL. V3.6.4 is now there and functioning as expected. Go ahead and deploy that one!

Thanks,
Tom

**Closed by tomweber-sas** 2020-12-18 19:54 UTC

**Comment by chunky** [comment] 2020-12-18 20:24
Tested and confirmed to be working from pypi upstream.

Thank you again!
