### ISSUE TITLE
How to write correct jar file path and JAVA env path in case of making a remote connection?

### ISSUE THREAD

**Issue by ghost** [sassoftware/saspy#171] opened 2018-09-20 09:28 UTC
My operating system : windows 7 professional 
My machine :  python 3.6
Remote machine operating system : windows 7 professional  SP1
SAS  9.4.1.0

I specified SAS _config_names as ['winiomwin'], and modified the winiomwin configuration in order to make a remote connection .

and I got errors as follows:

===============================================================
he OS Error was: 
系统找不到指定的文件。 (system cannot find specified file)
SAS Connection failed. No connection established. Double check you settings in sascfg.py file. 
Attempted to run program C:\Program Files\SASHome\SASPrivateJavaRuntimeEnvironment\9.4\bin\java.exe with the following parameters:['C:\\Program Files\\SASHome\\SASPrivateJavaRuntimeEnvironment\\9.4\\bin\\java.exe', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94210__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94210__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94210__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94210__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '51415', '-stdoutport', '51416', '-stderrport', '51417', '-iomhost', '110.241.112.151', '-iomport', '8561', '-user', 'pyfan27@xu.com.cn', '-lrecl', '1048576', ''] 
If no OS Error above, try running the following command (where saspy is running) manually to see what is wrong: 
C:\Program Files\SASHome\SASPrivateJavaRuntimeEnvironment\9.4\bin\java.exe -classpath "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94210__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94210__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94210__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94210__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\ProgramData\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 51415 -stdoutport 51416 -stderrport 51417 -iomhost 110.241.112.151 -iomport 8561 -user pyfan27@xu.com.cn -lrecl 1048576   
No SAS process attached. SAS process has terminated unexpectedly. 
No SAS process attached. SAS process has terminated unexpectedly. 
No SAS process attached. SAS process has terminated unexpectedly.
============================================================

I think i wrote  wrong JAR files path  in sascfg_personal.py ,   so how to write correct four remote jar file paths  in  cpW variable?  
i confused that saspyiom.jay is not existed on remote machine but on my local machine, how to write the path of this?
 and what about java environment? My local machine  has no JAVA env , i want to use java environment on remote machine.

**Comment by tomweber-sas** [comment] 2018-09-20 14:48
Hey @gxzhf, First, the error is that it cannot find the java.exe you've specified:
```
C:\Program Files\SASHome\SASPrivateJavaRuntimeEnvironment\9.4\bin\java.exe
```
You mention that you're trying to use java on the remote machine? That won't work. Java needs to be on the machine saspy (python) is running on. Also the jars have to be on your machine also. Your machine that you are running saspy on is the client; it uses java and those jars (they are the SAS IOM client) to connect from your machine to the remote SAS workspace server. If the 4 jars are remote on the SAS server, you can copy them to your client machine so that those 4 and saspyiom.jar are all on your machine where you're running saspy. You'll need in install Java on there too, but that's easy, and free.

Once you have that, then just change your classpath to be the correct paths to where you put those jars, and the path where java.exe is. It looks like you specified the paths correctly, they just aren't really there on your machine. But they are specified ok, as it looks like this:
```
-classpath "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94210__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;
            C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94210__prt__xx__sp0__1\deploywiz\log4j.jar;
            C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94210__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;
            C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94210__prt__xx__sp0__1\deploywiz\sas.core.jar;
            C:\ProgramData\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j
```
which would be right if they were actually there in those paths.

Does that make sense?
Thanks
Tom

**Comment by gxzhf** [comment] 2018-09-21 01:34
Thanks for your quick response！ I am clear with these problems and it does work.
When I run code with command"sas=saspy.SASsession()",
a new type of error appears that "
 JAVA error:
java.lang.UnsupportedClassVersionError:pyiom/saspy2j:Unsupported major.minor version 51.0
(...............)
'''
does that mean I used a incorrect version of Java?
My java version is :
version 6 update 29 (build 1.6.0_29-b11)

**Comment by tomweber-sas** [comment] 2018-09-21 02:39
I am not at my computer right now too look, but I think you are right that Java 6 is too old and that is this problem. I think I ran into that recently. Can you download current Java? 8 I think. 
Glad you are almost there! I think you'll be up running soon. 
Tom

**Comment by gxzhf** [comment] 2018-09-21 02:40
I think I have solved the java version problem....
but it still appears another error:
 ""
 We faileded in getConnection
The application could not log on to the server "110.241.xxx.xxx:8591".No server is available at that port on that machine
。。。。。
“”
On the remote machine, I commonly use SAS EG to process data.
So how could I make sure that the SAS service is activate on the remote machine?  and how to get its port?

**Comment by tomweber-sas** [comment] 2018-09-21 02:42
Ah, that is better. So the host must be that of the object spawner and the port the workspace server port. Sometimes people have the metadata server host or port by accident.

**Comment by tomweber-sas** [comment] 2018-09-21 02:47
And, here's the doc on how to find object spawner and workspace host and port.
https://sassoftware.github.io/saspy/advanced-topics.html#using-proc-iomoperate-to-find-object-spawner-hosts-and-workspace-server-ports

**Comment by tomweber-sas** [comment] 2018-09-21 02:51
If you have more than one workspace server you can connect to in EG, you should see them in the IOM operate output. You use the 'appserver' key in your configuration definition to select the specific one. See the IOM Remote doc for that,  if that's the case.
Tom

**Comment by gxzhf** [comment] 2018-09-21 03:18
I am sorry that I am not familar with SAS ...
According to the docs that you gave me I wrote the SAS code like this :

proc iomoperate
  uri="iom://127.0.0.1:8591;Bridge;USER=pyfan27@xu.com.cn,PASS=my12345678";
  list DEFINED FILTER="Object";
quit;

it does not work , and SAS gave me errors

**Comment by gxzhf** [comment] 2018-09-21 06:17
I changed the uri="iom://pdccjfdasdbs012.site;bridge;user=.......",  "pdccjfdasdbs012.site" is the host name I found........
 and then successfully excute the proc iomoperate.  The Machine Name the program returned to me is "pdccjfdasdbs013.site",
I put "pdccjfdasdbs013.site" for the 'iomhost' key. and I found the workspace server port 8591 for the 'iomport' key, and start a SASsession() again...
got error like this:
""
We faileded in getConnection
The application could not log on to the server "pdccjfdasdbs013.site:8591".The machine name is not valid.
。。。。。
“”

but ,  the reponse did return the Machine Name as "pdccjfdasdbs013.site"

**Comment by tomweber-sas** [comment] 2018-09-24 00:41
Can you try the fully qualified host name? All 4 parts, not just 2. Or use the IP address. I haven't seen that error before, so that's what I would do first.
Thanks,
Tom

**Comment by gxzhf** [comment] 2018-09-24 06:40
"pdccjfdasdbs013.site" is the  fully qualified host name I received. It only have 2 parts. 
I dont know how find the IP address of  the object spawner.
Wait for me I'll goto my office tomorrow and get some screenshots for you.

**Comment by tomweber-sas** [comment] 2018-09-24 14:50
@gxzhf you can use the nslookup command to get the IP address.
```
nslookup pdccjfdasdbs013.site
```
Tom

**Comment by gxzhf** [comment] 2018-09-25 01:10
@tomweber-sas,
I use the command"nslookup pdccjfdasdbs012.site" in CMD on my local machine, and it shows the "
“"
Server:Unknown
Address:84.32.145.2 
*** UnKnown  Notfound pdccjfdasdbs012.site :Non-existent dimain
""
So I set the 'iomhost' to '84.32.145.2 ' and run , and it appears
" No server is availale at that port on that machine"

I also tested the IP and port by using command: 
'ping 84.32.145.2'  and I got 4 replies from this host, time=10ms, TTL=244 ,etc...
'telnet 84.32.145.2 8591','telnet 84.32.145.2 8561': by running these two commands ,
It says"connecting...84.32.145.2.... Unable to open connection to host. Connect failed on port 8591/8561"

**Comment by gxzhf** [comment] 2018-09-25 01:19
I suspect that 'pdccjfdasdbs012.site' is not the correct host at all

**Comment by tomweber-sas** [comment] 2018-09-25 13:06
Well, the result from that nslookup isn't very promissing. That ip address you are getting is that of the DNS server that was used to try to resolve the name; which it didn't. It's no surprise that address will be the same. The actual output, with a resolvable name would have the fully qualified name and ip address of that host you are looking up after the Server: and Address: of the DSN server it used to look it up.
That's not in your output above.  If you try it with a name that can be found you would see the rest of the information, something like htis:
```
C:\Users\sastpw>nslookup tomspc
Server:  dns1vip-1019.net.sas.com
Address:  10.19.1.23

Name:    d10a626.na.sas.com
Address:  10.23.16.149
Aliases:  tomspc.na.sas.com
```

Is there someone who administers the SAS servers you are trying to connect to who can give you the correct name/ip and port you need? 

Thanks,
Tom

**Comment by gxzhf** [comment] 2018-09-28 06:15
Unfortunately, the person who help us to install the SAS software has been left the company and he was just followed the installation instructions of book, also not famalier with this.
Based on what you saying,,I confused what the SAS server actually is.
Our company 's data all stored in Data Warehouse in Shanghai(Another city),  and in our branch office here ,there is a shared machine with SAS9.4 and SASEG installed, and we all remotely connect to this machine through our personal computers to access our company's data.
So ,what do you mean the SAS server you have mentioned before ? refers to SAS in Shanghai or the SAS installed in that shared machine in our office?
If the SAS server refers to SAS9.4 installed in the shared computer, now I really don't know that the correct name and port of it...  Any other methods to get these information(host name and port )?
Thank you Tom!

**Comment by tomweber-sas** [comment] 2018-09-28 12:47
Ok, well that helps a little. So it sounds like the SAS you want to connect to is a workspace server in Shanghai.
Is that right? Sounds like the way you do this currently is from the shared machine that has both a local SAS9.4
install and the EG client. So, how do you access the DW (Data Warehouse) SAS workspaces servers today?
Do you use EG? Do you use that local SAS and run code that connects to the remote system from in that SAS session?

How do you connect to that local SAS/EG machine from your own machine? Remote desktop?
Do you use VPN to get your local machine onto the company network?

Where do you have saspy installed? When you tried to look up the ip address of that pdccjfdasdbs012.site,
were you on the SAS/EG machine, on your companies network? Or from your own machine not on the network?

You say you ran proc iomoperate with this addr (which had to be the metadata server machine)
pdccjfdasdbs012.site;. I haven’t seen what the output from that is. Where did you run that?
Local SAS or EG, I assume? 

I’m starting to think (guess because I don’t have the information) that you have saspy on your personal
machine which isn’t on your companies network and you’re trying to connect to your DW server?
Is that what you’re trying? 

It sounds to me like you should be trying to run saspy on the machine you currently use to connect
to the place you want, where the other SAS clients are; the SAS/EG machine. EG is just a client
like saspy. If the saspy machine isn’t on the network you’re trying to get at, it won’t be able to connect. 

Can you confirm any of this?

Thanks!
Tom

**Comment by gxzhf** [comment] 2018-09-29 03:34
Ok, well that helps a little. So it sounds like the SAS you want to connect to is a workspace server in Shanghai.
Is that right?[Not exactly right. Exactly speaking, I am not sure the SAS I want to connect to is whether the SAS server in Shanghai or SAS in shared computer in our office.] Sounds like the way you do this currently is from the shared machine that has both a local SAS9.4
install and the EG client. So, how do you access the DW (Data Warehouse) SAS workspaces servers today? 
Do you use EG?[Yes, My colleagues and I all use SAS-EG installed on that shared machine by using remote desktop connection to access DW stored in Shanghai everyday. ] Do you use that local SAS and run code that connects to the remote system from in that SAS session?[ Sorry that I don't quite understand what you mean here.]
How do you connect to that local SAS/EG machine from your own machine? Remote desktop?[Yes, connect to the local SAS-EG machine by using remote desktop]
Do you use VPN to get your local machine onto the company network?[I am sorry I don’t know what the VPN is , our personal office computers and that shared computer are all in the same company network. The shared computer is actually the same as our computers, except that everyone can use the above SAS-EG via remote desktop connection]
Where do you have saspy installed? [My personal office computer.]When you tried to look up the ip address of that pdccjfdasdbs012.site,
were you on the SAS/EG machine, on your companies network? [I tried it on both way .I tried to run the command ”nslookup pdccjfdasdbs012.site” both on my own computer and the shared computer, the results are the same] Or from your own machine not on the network?[Maybe I did not make it clear before, my own machine refers to my own office computer, this computer and shared computer are all in the same company network.]
You say you ran proc iomoperate with this addr (which had to be the metadata server machine)
pdccjfdasdbs012.site;. I haven’t seen what the output from that is. Where did you run that? Local SAS or EG, I assume? [I ran proc iomoperate in SAS-EG environment in that shared computer. Btw,,What do you mean of “Local SAS” here? Forgive me for my bad English ^_^ ]

I’m starting to think (guess because I don’t have the information) that you have saspy on your personal
machine which isn’t on your companies network and you’re trying to connect to your DW server?[My personal machine I mentioned before is my office computer, They are all in the same company network]
Is that what you’re trying?
It sounds to me like you should be trying to run saspy on the machine you currently use to connect to the place you want, where the other SAS clients are; [This may be useful,  however, my purpose is let everybody to access our company’s data by using saspy package in their own office computer instead of remote desktop connection, because more than one people cannot remotely connect to that shared machine at the same time. So, if I could access company’s data in my own office computer, everyone else can do this in their own computers, it will greatly improve our work efficiency. ]
the SAS/EG machine. EG is just a client like saspy. If the saspy machine isn’t on the network you’re trying to get at, it won’t be able to connect.
[
My office computer have saspy installed.
The shared computer in our office:  have SAS9.4 and SASEG installed.
The DW I want to access may located in computer room in Shanghai.
]
Can you confirm any of this?[Yes, I have confirmed what I can confirm. If you have any questions about what I said, please tell me . Thank you so much!]

**Comment by tomweber-sas** [comment] 2018-10-01 13:56
Ok, that does clarify this, thanks! Yes, what you are looking for can work. Each using saspy on their own work computer. Each computer needs saspy installed, the jars from your SAS9.4 install copied over and pointed to in the classpath in the sascfg_personal.py file. That should all be fine.

The problem currently is that you don't have a valid hostname for the object spawner. Not even the EG machine, can resolve the name you are trying to use. We need to have a valid host name or IP.

Can you show me the results from both proc iomoperate runs? If you don't want them displayed here, you can email them directly to me. Do both queries:
list DEFINED FILTER="Object";
and
list DEFINED FILTER="- Workspace";

Also, can you correlate what you see in those with your EG configuration to be sure you're pointing to the correct metadata server? 

Thanks!
Tom

**Comment by gxzhf** [comment] 2018-10-06 07:08
OK. I will try this the day after tomorrow. Thanks!

**Comment by gxzhf** [comment] 2018-10-08 01:13
With running the command
"
proc iomoperate;
list DEFINED FILTER="Object";
quit;
"
and 
"
proc iomoperate;
list DEFINED FILTER="-Workspace";
quit;
",
got same error "ERROR: Not connected to an IOM Server that supports the LIST DEFINED SERVERS command."
Thanks.

**Comment by tomweber-sas** [comment] 2018-10-08 01:39
How did you get results before?
________________________________

**Comment by gxzhf** [comment] 2018-10-08 05:58
What results? When I click that ,  it jumps to the head of this page..

**Comment by tomweber-sas** [comment] 2018-10-08 14:35
Earlier in this thread you said you ran the proc operates and saw pdccjfdasdbs012.site. I didn't see any results from those runs, so I was asking if you can run those 2 queries again and let me see the actual results so maybe I could see something useful. You said then that you got results, not an error (copied that below)?

The only  thing I have to go on so far is that you get an error that the hostname:port isn't valid.
That host name can't be resolved on any computer you have, and we can't get the IP address of the machine to use that IP directly instead of a host name, and I don't have any other information to go on. 

Your install and configuration of saspy appear ok, as far as I can tell, given that you are trying to make a connection from the IOM client and getting a specific IOM error. It just appears you don't know the correct host name and/or port number.

Tom

> I changed the uri="iom://pdccjfdasdbs012.site;bridge;user=.......", "pdccjfdasdbs012.site" is the host name I found........
> and then successfully excute the proc iomoperate. The Machine Name the program returned to me is "pdccjfdasdbs013.site",
> I put "pdccjfdasdbs013.site" for the 'iomhost' key. and I found the workspace server port 8591 for the 'iomport' key, and start a SASsession() again...
> got error like this:
> ""
> We faileded in getConnection
> The application could not log on to the server "pdccjfdasdbs013.site:8591".The machine name is not valid.
> 。。。。。
> “”
> 
> but , the reponse did return the Machine Name as "pdccjfdasdbs013.site"

**Comment by gxzhf** [comment] 2018-10-09 01:10
Yes, I did get results from those two queries, and I have sent those information to your personal email,thanks!

**Comment by tomweber-sas** [comment] 2018-10-09 13:13
Thank you, I've received them. I see 2 Object spawners that have Workspace server defined for them. However your Workspace server query returned no information, so I can't correlate any workspace server (nor ports) with either of those object spawners. I also couldn't be sure of the machine name for one of the object spawners, but suspect I have it right. Here's the object spawner info I saw. Can you confirm the machine for pdccjfdasdbs022 is actually pdccjfdasdbs002.site?

```
Object Spawner - pdccjfdasdbs022  (A5EF2RZL.AU00000G)
-component  - SASAppEM - Workspace Server
-machine       - ? pdccjfdasdbs002.site

Object Spawner - pdccjfdasdbs015  (A5EF2RZL.AU0000T3)
-component  - SASAppD - Workspace Server
-component  - SASAppDUTF8 - Workspace Server
-machine       - pdccjfdasdbs015.site
```

Your query for the Workspace server didn't have a valid search string. The search is a simple byte by byte compare, so the problem was using '-Workspace' instead of '- Workspace' or just 'Workspace'. The '-' and 'W' were beside each other with no space between.
Can you run that again so we can see the workspace servers?

I expect you are trying to use the SASAppEM, which seems like the machine name listed is pdccjfdasdbs002.site, and I can't confirm the port until there are results for the Workspace query. but, 8591 is the default, and probably what we'll see. 

Assuming all of this is right, it still looks like it's a DNS problem with only using 'pdccjfdasdbs002.site' where the're more to the name that's not being specified. Some of the machine names in the output don't even have '.site', only pdccjfdasdbsNNN as the name. These machine names are just strings someone typed into the metadata. They are not necessarily fully qualified machine names that will, by definition, be resolved by DNS on your client machine.

It still seems to me that you need to find out what the fully qualified name, or IP address, is for the object server. Do you have common DNS Suffixes that you use at your company? Do they use different ones on the Shanghai network? I'm expecting that you don't have the correct suffix configured in your DNS search on your client machines. 

I can't guess at what your suffixes are, but if nslookup can't find the name you are using then you can't connect to it because it's not a name that can be resolved. Odds are your suffixes would end in '.com', so for instance, instead of only pdccjfdasdbs002.site, it may be something like this that is really required; pdccjfdasdbs002.site.icbc.com but I have no idea what various suffixes your company uses. You have to find out the correct name, or ip, so DSN can find the machine you're trying to connect to.

So far everything else look like you have it configured right. It just looks like a DSN name issue.

Tom

**Comment by gxzhf** [comment] 2018-10-10 08:58
Firstly, with No. (A5EF2RZL.AU00000G), the result should be:
Object Spawner - pdccjfdasdbs022  (A5EF2RZL.AU00000G)
-component  - SASAppEM - Workspace Server
-machine   name    -  pdccjfdasdbs022.site
and  I  am trying to use SASAppd and SASAppdUTF8.
BTW,I feel that I am on the verge of success.  Today, I went through the SAS-EG installation manual and I found a server' ip information list that every pdccjfdasdbs0xx.site corresponds with an IP address. I think these IP address should be the IOMhost I need. I put this IP address( which is related to 'pdccjfdasdbs015.site' that is the Machine Name for SASAppD and SASAppDUTF8) to 'iomhost' key and put 'iomport' as 8591 (I ran proc iomoperate 'Workspace' and found the port is 8591 of SASAppD), the program says "the userID(omruser) or password(omrpw) I provided is incorrect" instead of something  like 'no port open on that machine blabla...', 
So,,,, I think I have at least connected to the host computer, but the account number or password is wrong.  This user id and password can work in SAS-EG to access the company's DW. Why is this?  Thank you.

**Comment by gxzhf** [comment] 2018-10-10 09:04
Is it possible that our organization has made some connection restrictions on SAS services for security reasons so that we cannot use saspy to connect to that SAS server?

**Comment by tomweber-sas** [comment] 2018-10-10 12:39
Ok, great. having the IP address will work. BTW, you can then run nslookup ip_addr and you should see what the fully qualified name is. Also, no, there's no security to disable saspy, that I can imagine, I think you're just a little bit off still, but close.

So, with the output your got for 'Workspace', what port was the other (SASAppDUTF8) set to? Since they are both spawned by the same object server, I would think they should be configured for different ports, though I'm not positive on that point. If they are (even can be) the same, then you would need to use the 'appserver' key in your configuration definition to specify the name of the Workspace server (even if they are different, you can still set appserver to the correct name):
```
            'appserver' : 'SASAppD - Workspace Server'
or 
            'appserver' : 'SASAppDUTF8 - Workspace Server'
```
Again, those have to be spelled exactly right; I would cut-n-paste them :)

So, what I would try is all 3 workspace servers. I don't know which one you really connect to with EG, but if your credentials work with EG, and it's connecting to one of those, then I would try each of them. You need to specify the correct IP addr for the obj spawner that is used for that workspace server you're trying, the port for that workspace server and I would code the appserver as well.
It would seem that it should work for one of them at least. Can you see in EG what one you are really connecting to? I'm not familiar enough with EG to tell you how or where to look, but it's got to be in there to find what it's connected to (profile, server, ...?).
The other thing, given the naming of the 2 SASappD ones, you will need to specify the correct encoding in your configuration definition for everything to work correctly. I would assume SASAppDUTF8 is running SAS with encoding=utf8. But I don't know what the encoding is for SASAppD, nor SASAppEM.

If you get connected to one of them, you can submit your SASsession object to see what encoding the server is running and then correct it in your configuration definition, if it's not right. Like this:
```
import saspy
sas = saspy.SASsession()
sas
# submitting 'sas' would show something like this
Access Method         = IOM
SAS Config name       = iomj
WORK Path             = /sastmp/SAS_work0E5000000971_tom64-3/SAS_work178A00000971_tom64-3/
SAS Version           = 9.04.01M4P11092016
SASPy Version         = 2.2.9
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = WLATIN1
Python Encoding value = cp1252
```
I think you are finally getting there!
Tom

**Comment by gxzhf** [comment] 2018-10-11 02:31
With the output for 'Workspace', SASAppD and SASAppDUTF8 did have different ports. And I checked their encodings in SAS-EG, SASAppD  is running with encoding='euc-cn' and SASAppDUTF8 with 'utf-8'.
So in theory I don't need to specify app server(Even if I specified this app server).

Now, I assume that I have correctly configured the IOMhost(My colleagues in Shanghai once again checked the IP corresponding to the host computer pdccjfdasdbs015.site for me), the IOMport (what I found in the output for 'Workspace') ,the encoding and the appserver. I also specified the 'omruser' and 'omrpw' which can work in SASEG.

However, all problems here seem to be a user id/pw problem so that I cannnot establish this connection. Is it possible that this so-called userID/PW I currently use is not the omruser and omrpw?

**Comment by gxzhf** [comment] 2018-10-11 02:58
One other thing, When I run nslookup ip_addr and I didn't see what the fully qualified name is, that's strange.  I can use command "ping this_ip" and get the responses.
'this_ip'  is the IP address of the DW server in Shanghai, and I think this IP is the IP I should connect to.

**Comment by gxzhf** [comment] 2018-10-11 07:06
Also, is SASPY and SA SEG essentially the same thing, both clients of SAS?
except that SASEG provides a visual environment and SASPY provides a Python interface?

**Comment by tomweber-sas** [comment] 2018-10-11 16:43
Ok, so first, yes EG and saspy are both clients that connect to Workspace servers via IOM. However, they are very different and don't use the same code to do so. EG used the .Net IOM client interface while saspy used the Java IOM client interface. But, from a logical standpoint, yes they both connect to an object spawner and request a workspace server, so it is that same from that point. And, many people use this without issue, same host:port and credentials as EG. So, we just need to figure out what's going on with your scenario.

Now that we have the right configuration info, can you show me the 3 configuration definition you have for the 3 workspace servers. And, can you show me the code you submit and the full results you get (the errors) for each of the 3? Also, what version of saspy are you using? I looked back through all of this but didn't see. 

I saw that your ports were 8591 (022 EM), 8591 (015 D) and 28591 (015 DUTF8). For D, with SAS euc-cn, you should have 'encoding' : 'gb2312' in your config definition, and for DUTF8,  'encoding' : 'utf8'. 

The next thing, if I can't see anything from your attempts and the errors, would be to get the Object spawner logs to see what they show. But, lets see what you are getting first.

Again, you can post here or email of you prefer.

Thanks!
Tom

**Comment by gxzhf** [comment] 2018-10-12 01:56
My saspy's version is '2.2.8'.  Actually, I only use D and DUTD8 these 2 workspace servers. So I sent my code and corresponding results of these two to your email.  Thanks!

You mentioned that "And, many people use this without issue, same host:port and credentials as EG.", Does it mean that some of the settings I can use in EG include host IP, ports, credentials to connect via saspy?

**Comment by tomweber-sas** [comment] 2018-10-12 13:51
Ok, so everything you're doing looks good. You have a good version of Java, of saspy, you seem to have the right host and ports. Now it is a matter of the credentials you are using. 

To your question, like I described that EG and saspy are both clients that connect to workspace servers, though they are written differently. To connect to a workspace server, you have to connect to the object spawner which is configured in metadata (OMR) to launch that workspace server. You have to have the hostname/ip of the object spawner and the port for the workspace server. You also have to have credentials, defined in OMR, having appropriate authority to be allowed to connect to that objspawner and launch the workspace server. In that regard, host:port and id/pw are the same (in the end) between EG and saspy. I think that EG actually connects to OMR, with the credentials you provide, to get the host:port of the obj/wrkspc, which is different from saspy. saspy doesn't connect to OMR. You just provide the obj/wrkspc host:port. But, the metadata id/pw has to be defined in OMR with authority to use that workspace server for both clients.

As for exactly how/where EG is configured to have that information, I'm not 100% sure, as I don't use it. But, it has to have the host:port id/pw that are valid to be able to work, same as saspy. So, we need to focus now on the id/pw you are using. It would appear, from the very clear IOM error messages, that you are now connecting to an object spawner with the workspace server port (or you would be getting the other message about wrong host or port), but the id/pw you are providing are not defined in OMR as credentials or they are and they do not have permission to run that workspace server.

Since you can access that server from EG, I have to believe that the id/pw that EG is using to connect is not the same as you're providing to saspy. 

In your proc iomoperate back at the beginning of this thread, the id passed in didn't look like the id you have in these connection attempts. Not the same, and not really the same format.

Can you verify the OMR userid and Password you are using. If you have SAS Management Console you can connect to OMR and validate all of this. You haven't mentioned SMC before, so I don't know if you use that or not. That how you can see all of this metadata configuration.

I think you just aren't using the correct ip/pw. If you can't find the id/pw that is being used by EG and can't use SMC to look it up either, perhaps the administrators in Shanghai, can look and provide you the correct credentials?

Also, even though the 2 workspace servers are defined on different ports, I would try it with and without the appserver key just to be sure (until it works then you'll know if it's needed or not). It's still the same object spawner and I can't swear that it isn't necessary when that spawner has multiple workspace servers defined. It wouldn't seem that you would need to, but I would still try it both ways in case. Be sure to match up the correct name with the port:
 8591 - 'SASAppD - Workspace Server'
28591 - 'SASAppDUTF8 - Workspace Server'

Tom

**Comment by gxzhf** [comment] 2018-10-15 02:15
@tomweber-sas,
I haven't used  SAS Management Console(SMC) before. And I didn't find SMC tool in that EG machine either."USER=pyfan27@xu.com.cn,PASS=my12345678" is just simulated in previous proc iomoperate. So don't need to worried about that...
 Administrators in Shanghai may know how to check these information in SMC, but I don't think they will show me OMR's id and password.
So ,
1> Can I enter SMC in EG machine?  That EG machine also has SAS9.4 installed. If SMC is part of SAS9.4 ,I should find a way to get into SMC.
2>  If I cannot enter SMC in EG machine, is there any other way to enter SMC or get OMR's id/pw? Such as cmd commands or .....?
If none of these methods works, I think I cannot connect to company's DW via saspy..
Thanks!

**Comment by gxzhf** [comment] 2018-10-22 07:45
I do use same credentials between using saspy and running proc iomoperate from EG.
I checked the EG machine , and it has not SMC installed. It is also unrealistic to ask other departments to install SMC for me.
I need to spend a little longer time reading the doc you gave me about PROC METADATA (In theory, can I get the OMR‘s id/pw with the correct PROC METADATA command even if I don't have enough permission? ), and maybe in the end my leader would help me to ask for the OMR's id/pw.
So, Thank you. If you feel that it should close this issue, then close it.

**Comment by gxzhf** [comment] 2018-10-22 09:30
Why was my post automatically deleted? OK, I'll send it again:

I do use same credentials between using saspy and running proc iomoperate from EG.
I checked the EG machine , and it has not SMC installed. It is also unrealistic to ask other departments to install SMC for me.
I need to spend a little longer time reading the doc you gave me about PROC METADATA (In theory, can I get the OMR‘s id/pw with the correct PROC METADATA command even if I don't have enough permission? ), and maybe in the end my leader would help me to ask for the OMR's id/pw.
So, Thank you. If you feel that it should close this issue, then close it.

**Comment by tomweber-sas** [comment] 2018-10-24 19:38
I really don't understand how you would be getting the bad id/pw error from IOM if you are connecting to the same workspace server from EG. As for closing this, I'd really rather figure it out! 
The next step would be to get the object spawner logs and see what is in them when you try to connect. 
Those logs would be on the object spawner machine. Is that something you can coordinate w/ your server side people? 
Tom

**Comment by gxzhf** [comment] 2018-11-13 01:29
Hi, tom
you mean it should use the same id/pw to connect to  object spawner machine by using saspy or EG?, if so,  I also don't know where is incorrect. It seems that all the configurations are right!

**Comment by gxzhf** [comment] 2018-11-16 02:03
I checked the email and found I have sent the error about id/pw to you , the name of that email is "code and results", and it has been this mistake up to now...
I think I use same id/pw in these three scenes:
1>EG client
2>saspy configuration
3>PROC IOMOPERATE
Finally,  where can I found the object spawner logs?  Is it a log recorded in the backstage of the server in Shanghai? Because I use SASPY to connect, I should not see this log in my Python environment?
Thanks.

**Comment by gxzhf** [comment] 2018-11-19 02:40
Tom, I sent it again, please check that.

**Comment by tomweber-sas** [comment] 2018-11-26 18:10
Ok, I got email again, thanks. I do see that the error is that the credentials are not valid to log onto the machine the object spawner is on, or where it’s trying to run the workspace server. I’ve done an equivalent connection providing the wrong user name once and wrong password another time. I get the same error from IOM trying to connect. Also, the messages from the object spawner log show the issue, that the credentials are not correct. However, there is one extra message in the object spwaner log when it’s the userid that isn’t valid, which is not there when the userid is valid but the password is not. So, at least from that log you can identify if it’s the userid or the password that’s invalid, which you can’t tell from the IOM error returned to saspy.

The other possibility, which this isn't, would be that you didn't have permission in OMR to use that workspace server. But that would be a slightly different error message, about not being authorized to connect, as opposed to invalid credentials.

Same error messages from saspy (regardless of id or pw bad):
```
We failed in getConnection
The application could not log on to the server "localhost:8591". The user ID "tom" or the password is incorrect.


We failed in getConnection
The application could not log on to the server "localhost:8591". The user ID "sas" or the password is incorrect.
```

Messages written to the object spawner log (with default message level):
This was with a bad userid:
```
NOTE: 20181126:12.11.12.79: 00043332:NOTE: Unknown User Name.
NOTE: 20181126:12.11.12.79: 00043332:NOTE: Access denied.
WARNING: 20181126:12.11.12.79: 00043332:WARNING: New client connection (43) rejected from server port 8591 for user tom. Peer IP
         address and port are [::ffff:127.0.0.1]:42270 for APPNAME=SASPy.
NOTE: 20181126:12.11.12.79: 00043332:NOTE: Client connection 43 closed.
```

This was with a bad pw (no message about unknown user):
```
NOTE: 20181126:12.29.23.86: 00000704:NOTE: Access denied.
WARNING: 20181126:12.29.23.86: 00000704:WARNING: New client connection (6) rejected from server port 8591 for user sas. Peer IP
         address and port are [::ffff:127.0.0.1]:49386 for APPNAME=SASPy.
NOTE: 20181126:12.29.23.86: 00000704:NOTE: Client connection 6 closed.
```

**Comment by tomweber-sas** [comment] 2018-12-18 18:06
Were you ever able to get the object spawner logs? Could you see what user it was trying and whether it was the userid or pw that seemed wrong?

**Comment by gxzhf** [comment] 2019-01-03 07:48
Hi, tom 
I'm sorry I didn't come up to deal with this problem because I was busy with other affairs during this period. When I am free, I will study your reply again.Thanks!

**Comment by tomweber-sas** [comment] 2019-01-07 14:56
No problem. I know how it is to have other things to be working on. I'll be here whenever you have a chance to continue.
Tom

**Comment by tomweber-sas** [comment] 2019-05-21 17:27
Hey, did you ever figure out what credentials to use? Do you still need this issue open?

Thanks,
Tom

**Comment by tomweber-sas** [comment] 2019-05-23 16:31
If this is still a problem, feel free to reopen.

Thanks,
Tom

**Closed by tomweber-sas** 2019-05-23 16:31 UTC
