### ISSUE TITLE
saspy.SASsession.download no progress in getting file

### ISSUE THREAD

**Issue by rd5802** [sassoftware/saspy#290] opened 2020-04-09 12:32 UTC
I try to get data from my linux and windows SAS environments through IOM connection to Jupyter (linux)
Calling `download` function to get the files just creates local empty file but there is no progress.

**To Reproduce**
Windows SAS 9.4 server example:
 
`import saspy`
`sas = saspy.SASsession(cfgfile='/opt/SASPy/sascfg.py',cfgname='iomwin')`
`sas.download('file.sas7bdat','\path\to\file.sas7bdat')`
`# here, local file is created, but there is no progress`
`sas.dirlist('\path\to') # returns list of files in directory`

**Expected behavior**
A copy of remote file is created locally.

**Desktop (please complete the following information):**

`Access Method         = IOM`
`SAS Config name       = iomwin`
`WORK Path             = F:\TEMP\SAS_PROD\_TD17924_hostfg121_\Prc2\`
`SAS Version           = 9.04.01M5P09132017`
`SASPy Version         = 2.4.4`
`Teach me SAS          = False`
`Batch                 = False`
`Results               = Pandas`
`SAS Session Encoding  = wlatin2`
`Python Encoding value = cp1250`
`SAS process Pid value = 17924`

Maybe some other ports, other than SAS Workspace server, should be open to download the file?

**Comment by tomweber-sas** [comment] 2020-04-09 13:13
I can help you with this. First, sas.download returns a dict with ['Success', 'LOG'] as the keys. Can you show me what they had after you ran that; show the results of running that code? 
Can you run the sas.dirlist('/path/to') first, and even a sas.fileinfo('\path\to\file.sas7bdat')?
When you say no progress, do you mean it doesn't finish? or the file is empty after it runs?
Thanks,
Tom

**Comment by tomweber-sas** [comment] 2020-04-09 13:35
Here's my attempt to reproduce what I believe you're running. saspy on liinux and workspace server on Win. Of course, I'm running the current version of saspy, not 2.4.4, which is over a year old. Not jumping to any conclusions that whatever your seeing was fixed between these versions, as I don't know what you're getting yet; want to see what it is first. But, here's a sample run doing what I think your doing, so maybe you can show your run similarly. Oh, and, yes, for the IOM access method, the log isn't terribly telling, not like in the STDIO access method. Still, if there were an error, we ought to see that.

```
tom64-5> ll
total 8
drwxr-xr-x  2 sastpw r&d 4096 Apr  9 09:16 .
drwxr-xr-x 13 sastpw r&d 4096 Apr  9 09:16 ..
tom64-5> python3.5
Python 3.5.6 (default, Nov 16 2018, 15:50:39)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession(cfgname='iomjwin'); sas
SAS Connection established. Subprocess id is 24322

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to euc_kr based upon the SAS session encoding value of euc-kr.

Access Method         = IOM
SAS Config name       = iomjwin
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = C:\Users\sastpw\AppData\Local\Temp\SAS Temporary Files\_TD21844_d10a626_\Prc4\
SAS Version           = 9.04.01M4D11142016
SASPy Version         = 3.3.4
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = euc-kr
Python Encoding value = euc_kr
SAS process Pid value = 21844


>>> sas.dirlist(sas.workpath)
['sastmp-000000033.sas7bitm']
>>> sas.file_info(sas.workpath+'sastmp-000000033.sas7bitm')
{}
>>> sas.dirlist(sas.workpath)
['sastmp-000000033.sas7bitm', 'sasmac3.sas7bcat', 'sasgopt.sas7bcat']
>>> sas.file_info(sas.workpath+'sasmac3.sas7bcat')
{'Last Modified': '09Apr2020:09:23:30', 'Filename': 'C:\\Users\\sastpw\\AppData\\Local\\Temp\\SAS Temporary Files\\_TD21844_d10a626_\\Prc4\\sasmac3.sas7bcat', 'Create Time': '09Apr2020:09:23:10', 'LRECL': '32767', 'File Size (bytes)': '13312', 'RECFM': 'V'
}
>>> res = sas.download('test1', sas.workpath+'sasmac3.sas7bcat')
>>> res['Success']
True
>>> print(res['LOG'])
11                                      The SAS System            09:22 Thursday, April 9, 2020

220
221        filename _sp_updn 'C:\Users\sastpw\AppData\Local\Temp\SAS Temporary
221      ! Files\_TD21844_d10a626_\Prc4\sasmac3.sas7bcat' recfm=F encoding=binary lrecl=4096;
222
223
12                                      The SAS System            09:22 Thursday, April 9, 2020

226
13                                      The SAS System            09:22 Thursday, April 9, 2020

229
230        filename _sp_updn;
NOTE: Fileref _SP_UPDN has been deassigned.
231
232
>>> import os; os.listdir('.')
['test1']
>>> os.stat('test1')
os.stat_result(st_mode=33188, st_ino=7211541, st_dev=64768, st_nlink=1, st_uid=894, st_gid=100, st_size=13312, st_atime=1586438638, st_mtime=1586438638, st_ctime=1586438638)
>>>
SAS Connection terminated. Subprocess id was 24322
tom64-5> ll
total 24
drwxr-xr-x  2 sastpw r&d  4096 Apr  9 09:23 .
drwxr-xr-x 13 sastpw r&d  4096 Apr  9 09:16 ..
-rw-r--r--  1 sastpw r&d 13312 Apr  9 09:23 test1
tom64-5>
```

**Comment by rd5802** [comment] 2020-04-09 15:20
`sas.download` doesn't finish. I have to make a keyboard break to terminate it. This takes very long for very small files, so I assume that the transfer process doesn't start. Process activity on Jupyter side doesn't show that the work is beeing done.

I followed your code:

`import saspy`
`sas = saspy.SASsession(cfgfile='/opt/SASPy/sascfg.py',cfgname='iomwin')`

Please enter the IOM user id:  username
Please enter the password for IOM user :  ··············
SAS Connection established. Subprocess id is 194853

`!ls`
saspy_test.ipynb

`sas`
Access Method         = IOM
SAS Config name       = iomwin
WORK Path             = F:\TEMP\SASRisk_PROD\_TD24756_HOSTNAME_\Prc2\
SAS Version           = 9.04.01M5P09132017
SASPy Version         = 2.4.4
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin2
Python Encoding value = cp1250
SAS process Pid value = 24756

`sas.workpath`
'F:\\TEMP\\SASRisk_PROD\\_TD24756_HOSTNAME_\\Prc2\\'

`sas.dirlist(sas.workpath)`
['sastmp-000000008.sas7bitm',
 'sasmac4.sas7bcat',
 'sasmac1.sas7bcat',
 'sasgopt.sas7bcat',
 'regstry.sas7bitm']

`sas.file_info(sas.workpath+'sastmp-000000008.sas7bitm')`
{}

`sas.dirlist(sas.workpath)`
['sastmp-000000008.sas7bitm',
 'sasmac4.sas7bcat',
 'sasmac1.sas7bcat',
 'sasgopt.sas7bcat',
 'regstry.sas7bitm']

`sas.file_info(sas.workpath+'sasmac1.sas7bcat')`
{'Filename': 'F:\\TEMP\\SASRisk_PROD\\_TD24756_HOSTNAME_\\Prc2\\sasmac1.sas7bcat',
 'RECFM': 'V',
 'LRECL': '32767',
 'File Size (bytes)': '13312',
 'Last Modified': '09Apr2020:16:23:16',
 'Create Time': '09Apr2020:16:23:16'}

`res = sas.download('sasmac1.sas7bcat', sas.workpath+'sasmac1.sas7bcat')`

Here the process is stalled.

**Comment by tomweber-sas** [comment] 2020-04-09 15:40
And, when you cancel, IOM doesn't support the SAS Interupt Handler, like the STDIO method does, so you can't break out w/out terminating, and then you don't get a log. Hmm. 

Well, one thing to be sure of, is when you installed this release, are you using the saspyiom.jar that came with it, as opposed to having that jar (in your classpath) somewhere other than in the one in the repo where the new version would be picked up. Can you provide your classpath, or verify the path to that jar is the copy in the repo? That jar doesn't get updated often, but it did w/ the upload/download, so if you run the new python code with the old jar, I could see something like this happening. I've seen this be a problem a number of times before, and it's always difficult to diagnose, but an easy fix :)

If that's not it at all, is uninstalling that version and installing the current version something you can do? I still don't know of a reason that wouldn't work in the release you have. It's straight forward and I've looked through the changes since, and there's no 'fixes' for any problems like this. 

Check your classpath to be sure you're using the jar from the install, not an old one copied to somewhere else, first and let's be sure that's not it, or is it :) 

As you ran the same download I did, which doesn't take any amount of time, I agree that it's hung somehow and it's not that it's running and taking a long time. Seeing that other commands run normally, I'm just not coming up with a reason for this. You have permission in the current dir to write a file? it should return a failure if it can't, so again, not seeing what this is yet.

Tom

**Comment by tomweber-sas** [comment] 2020-04-09 15:50
BTW, with the current version of saspy, you no longer need to specify the classpath or copy those jars to your client or any of that. The 4 IOM client jars are finally part of the repo and the classpath is generated internally; keeping this problem about an old saspyiom.jar from being able to happen anymore! And, eliminating a lot of the configuration confusion with those jars and the classpath.

**Comment by rd5802** [comment] 2020-04-10 08:16
Well, well, well ...  It works :)  Created venv, pulled latest version of saspy and jars. Since I have an old sascfg.py, classpath is still set, but will clean it up.

Thanks for great support !!!

**Comment by tomweber-sas** [comment] 2020-04-10 12:42
Well, I wish I knew for a fact what the problem was and why it's fixed, but I'll take this :) Good way to end the week, haha. 

There have been a lot of improvements sine a year ago, so you might find some more functionality that you like in this new version too. A simple enhancement I really like is the submitLOG() and submitLST() methods. Same as submit() but they render the log and list (or log if no list or log and list,...) automatically, instead of returning the dict that you then have to display. Just nice and convenient. 
Let me know if you need anything else! I'll close this one now then.

Thanks,
Tom

**Closed by tomweber-sas** 2020-04-10 12:42 UTC

**Comment by rd5802** [comment] 2020-04-10 13:50
The problem was in jars. SASPy upgrade, without changing jar paths, did not make a difference. Thanks for info on new options.

R
