### ISSUE TITLE
My notebook word is Garbled

### ISSUE THREAD

**Issue by PistonIntJack** [sassoftware/saspy#136] opened 2018-05-26 07:32 UTC
Hi , I have 5 problems in saspy.

1. When I run the code.
%%SAS
proc print data=sashelp.class;
run;

data work.a;
  set sashelp.cars;
run;
I find some words are Garbled.
You can see in the picture.

![menu saveimg savepath20180526152757](https://user-images.githubusercontent.com/17619159/40573790-6575f446-60f9-11e8-92ed-fe74387b3d91.jpg)

2. When I run the code.
%%IML
a = I(6); * 6x6 identity matrix;
b = j(5,5,0); *5x5 matrix of 0's;
c = j(6,1); *6x1 column vector of 1's;
d=diag({1 2 4});
e=diag({1 2, 3 4});

How I can find this data ?
![menu saveimg savepath20180526153208](https://user-images.githubusercontent.com/17619159/40573820-018f624a-60fa-11e8-9753-39cafaf7766a.jpg)

3. Can I download the HR_comma_sep.csv ?

![menu saveimg savepath20180526162058](https://user-images.githubusercontent.com/17619159/40574185-d1162142-6100-11e8-9344-4c2dc59be81f.jpg)

4  The code "cars.heatmap('msrp','horsepower')" did not show picture. 
But the code "cars.tail() " or    "for col in ['horsepower','MPG_City', 'msrp']:
    cars.hist(col, title='Histogram showing '+col.upper())"
can show pictures.

![menu saveimg savepath20180527214606](https://user-images.githubusercontent.com/17619159/40599925-ff8bfbfa-6281-11e8-872f-780f2f5ada47.jpg)
![menu saveimg savepath20180527214720](https://user-images.githubusercontent.com/17619159/40599914-f910ab5e-6281-11e8-8884-604345ecae86.jpg)

5. If I have a hr.sas7bdat  in E: , how do I load in my python?
I have read the documentation. But I can not load it.

thank you

**Comment by tomweber-sas** [comment] 2018-05-29 14:07
Yes, I can help with these. 

1)	This is a transcoding issue. Since you submitted this with the magic, I can’t see what SASsession it’s using. You have a SASsession object in later code (sas). Can you submit that ‘sas’ object and it will display a what version you’re running, what encodings you’re using …
I see a tail() method run later with that sas session (of the cars data set), and I don’t see any transcoding issues with that.
I believe you’re using your ‘winlocal’ config? Is that the only one available in your config file? If not, I would have expected you’d be prompted for which one to use when you submitted %%SAS. 
Can you submit the following and see if the output is different?
```
# first cell
from IPython.display import HTML  # so we can see the html output later
sas

# next cell
ll = sas.submit(“proc print data=sashelp.class; run;”)
HTML(ll[‘LST’])
```

2)	I don’t know what this iml code is supposed to do. But when I run this it displays the SASLOG, as there’s apparently no output produced.
Can you submit this again and in the next cell retrieve the log so we can see what happened (the proc iml should be the last thing in the log):
```
# first cell
%%IML
a = I(6); * 6x6 identity matrix;
b = j(5,5,0); *5x5 matrix of 0's;
c = j(6,1); *6x1 column vector of 1's;
d=diag({1 2 4});
e=diag({1 2, 3 4});

# next cell
print(sas.saslog())
```

3)	This seems to be getting an error on the Pandas read_csv method saying it can’t find the file. I guess double check the path you’re giving Pandas?

4)	Since the histograms ran, I don’t know why the heatmap method wouldn’t. We’ll need to look at the log and see if there was an error.
Can you submit the heatmap method in one cell, and then get the log in the next cell (that way the code for the heatmap will be the last thing in the log).
```
# first cell
cars.heatmap('msrp','horsepower')

# next cell
print(sas.saslog())
```
5)	If you don’t have a libref already for your E: path, then you can assign a libref with the saslib method of the SASsession object.
Then you can access your SAS  Data Set via that libref.
```
# assign the SAS library containing the hr data set
sas.saslib('Elib', " 'E:\' ")

# assign a SASdata object for your data set
hrdata = sas.sasdata(‘hr’, ‘Elib’)
# now you can access that data; hrdata.head() or whatever.

# if you’re trying to pull the data into python as a data frame, just submit
hr_df = hrdata.to_df()  # or hrdata.to_df_CSV() 
```

Thanks,
Tom

**Comment by PistonIntJack** [comment] 2018-05-29 14:39
Thank you. Tom.
question 1. 
I use winlocal.
I find I used zh config. when I use u8 config. this question is disappear.
But I have a new question.
![menu saveimg savepath20180529223858](https://user-images.githubusercontent.com/17619159/40665926-1dee3c74-6391-11e8-91d6-4ea3fffd53c9.jpg)
![menu saveimg savepath20180529223835](https://user-images.githubusercontent.com/17619159/40665943-2664616c-6391-11e8-8015-1ea9066bb61e.jpg)

**Comment by tomweber-sas** [comment] 2018-05-29 15:26
@PistonIntJack  Ok, for number 1, what is zh config? Can you submit your 'sas' (SASsession object) so I can see the information. Also, can you show me your winlocal config?
number 3. Ok, I see. Jared wrote that part of the doc (getting started). I'm not sure what data he used for those examples. I will look into that and let you know. You can use any csv file, though. Just change the column names for some of the examples so they are columns in your data. You can write out a sas dataset as csv if you want, to play around with the various methods, in the mean time while I track down the data he used/
```
cars.to_csv('some/path/cars.csv')

#then you can use 'some/path/cars.csv' in the examples
hr_pd = pd.read_csv("some/path/cars.csv")
# just use column names from the cars dataset in the rest of the methods.
``` 
For number 4, there is an error, but I don't know what it says:
ERROR 180-322: 语句无效或未按正确顺序使用。
Can you tell me what the error is?

Thanks,
Tom

**Comment by tomweber-sas** [comment] 2018-05-29 17:18
Ok, will catch up with you tomorrow. For now, I want to see where we are. This is what I think currently.

1) wrong encoding, so saspy was trying to transcode when it shouldn't.
   This is fixed
2) Did you see what was in the log after submitting %%IML?
   This is still open. But, it could be a problem caused by 1 (don't know yet, need info)
3) Found the csv file on kaggle
   This is fixed or rather addressed
4) Got the error from the log, though it doesn't appear correct; statements are ok.
   This also could be something with the encodings being mismatched. Could be a bad character in the input do to transcoding that shouldn't have been done. Don't know still. Try again with the fix for 1
5) I believe you said you understand this now.
   This is fixed or addressed

 Have a good night. Let me know if only 2 and 4 are still issues, and whether fixing the encoding fixed or changed their behavior.

Thanks,
Tom

**Comment by PistonIntJack** [comment] 2018-05-30 09:19
Thank you Tom.
question 1, 3, 5 are addressed.

I find my sas log is Chinese.  I modify u8 sasv9.   LOCALE changed from zh_CN to en_US. When I start my sas SASsession in SAS. Log is English. But when I start in Jupyter. Log is Chinese. So I change my encoding.

my sas
Access Method         = IOM
SAS Config name       = winlocal
WORK Path             = C:\Users\Jack\AppData\Local\Temp\SAS Temporary Files\_TD1048_JACKPC_\Prc2\
SAS Version           = 9.04.01M2P07232014
SASPy Version         = 2.2.4
Teach me SAS          = False
Batch                 = False
Results               = HTML
SAS Session Encoding  = WLATIN1
Python Encoding value = latin1



question 2 
I think that there’s apparently output produced in the last week.  I miss understand the iml. I think the question is fixed. The code and log  is below.

 
question 4
The question is still exists. I think that it is not encoding problem. The code and log  is below.

Sorry my txt file cannot Upload to the github. So I copy my log.


question 2 code
![menu saveimg savepath20180530171215](https://user-images.githubusercontent.com/17619159/40711003-ad142d8c-642c-11e8-9e6c-04bad12592af.jpg)


question 2 log



1                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

NOTE: Copyright (c) 2002-2012 by SAS Institute Inc., Cary, NC, USA. 
NOTE: SAS (r) Proprietary Software 9.4 (TS1M2) 
      Licensed to MICHIGAN STATE UNIVERSITY-T&R-SFA, Site 70082953.
NOTE: This session is executing on the X64_8PRO  platform.



NOTE: Updated analytical products:
      
      SAS/STAT 13.2
      SAS/ETS 13.2
      SAS/OR 13.2
      SAS/IML 13.2
      SAS/QC 13.2

NOTE: Additional host information:

 X64_8PRO WIN 6.2.9200  Workstation

NOTE: SAS Initialization used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      
1          ;*';*";*/;
2          options svgtitle='svgtitle'; options validvarname=any pagesize=max nosyntaxcheck; ods graphics on;
3          
4          ;*';*";*/;
5          %put E3969440A681A2408885998500000001;
E3969440A681A2408885998500000001
6          
2                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

7          ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
7        !  outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
8          ;*';*";*/;
9          libname work list;
NOTE: Libref=   WORK 
      Scope=    IOM ROOT COMP ENV
      Engine=   V9
      Access=   TEMP
      Physical Name= C:\Users\Jack\AppData\Local\Temp\SAS Temporary Files\_TD1048_JACKPC_\Prc2
      Filename= C:\Users\Jack\AppData\Local\Temp\SAS Temporary Files\_TD1048_JACKPC_\Prc2
10         
11         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
12         
13         %put E3969440A681A2408885998500000002;
E3969440A681A2408885998500000002
14         
3                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

15         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
15       !  outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
16         ;*';*";*/;
17         %put SYSV=&sysvlong4;
SYSV=9.04.01M2P07232014
18         
19         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
20         
21         %put E3969440A681A2408885998500000003;
E3969440A681A2408885998500000003
22         
4                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

23         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
23       !  outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
24         ;*';*";*/;
25         proc options option=encoding;run;

    SAS (r) Proprietary Software Release 9.4  TS1M2

 ENCODING=WLATIN1  Specifies the default character-set encoding for the SAS session.
NOTE: PROCEDURE OPTIONS used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      

26         
27         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
28         
29         %put E3969440A681A2408885998500000004;
E3969440A681A2408885998500000004
30         




 question 4 code

![menu saveimg savepath20180530171434](https://user-images.githubusercontent.com/17619159/40711198-2a08d702-642d-11e8-8f85-0e96e46d8d6d.jpg)



 question 4 log

1                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

NOTE: Copyright (c) 2002-2012 by SAS Institute Inc., Cary, NC, USA. 
NOTE: SAS (r) Proprietary Software 9.4 (TS1M2) 
      Licensed to MICHIGAN STATE UNIVERSITY-T&R-SFA, Site 70082953.
NOTE: This session is executing on the X64_8PRO  platform.



NOTE: Updated analytical products:
      
      SAS/STAT 13.2
      SAS/ETS 13.2
      SAS/OR 13.2
      SAS/IML 13.2
      SAS/QC 13.2

NOTE: Additional host information:

 X64_8PRO WIN 6.2.9200  Workstation

NOTE: SAS Initialization used (Total process time):
      real time           0.01 seconds
      cpu time            0.01 seconds
      
1          ;*';*";*/;
2          options svgtitle='svgtitle'; options validvarname=any pagesize=max nosyntaxcheck; ods graphics on;
3          
4          ;*';*";*/;
5          %put E3969440A681A2408885998500000001;
E3969440A681A2408885998500000001
6          
2                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

7          ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
7        !  outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
8          ;*';*";*/;
9          libname work list;
NOTE: Libref=   WORK 
      Scope=    IOM ROOT COMP ENV
      Engine=   V9
      Access=   TEMP
      Physical Name= C:\Users\Jack\AppData\Local\Temp\SAS Temporary Files\_TD12276_JACKPC_\Prc2
      Filename= C:\Users\Jack\AppData\Local\Temp\SAS Temporary Files\_TD12276_JACKPC_\Prc2
10         
11         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
12         
13         %put E3969440A681A2408885998500000002;
E3969440A681A2408885998500000002
14         
3                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

15         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
15       !  outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
16         ;*';*";*/;
17         %put SYSV=&sysvlong4;
SYSV=9.04.01M2P07232014
18         
19         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
20         
21         %put E3969440A681A2408885998500000003;
E3969440A681A2408885998500000003
22         
4                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

23         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
23       !  outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
24         ;*';*";*/;
25         proc options option=encoding;run;

    SAS (r) Proprietary Software Release 9.4  TS1M2

 ENCODING=WLATIN1  Specifies the default character-set encoding for the SAS session.
NOTE: PROCEDURE OPTIONS used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      

26         
27         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
28         
29         %put E3969440A681A2408885998500000004;
E3969440A681A2408885998500000004
30         
5                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

31         ;*';*";*/;
32         data _null_; e = exist('sashelp.cars');
33         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.02 seconds
      cpu time            0.00 seconds
      

34         
35         
36         ;*';*";*/;
37         %put E3969440A681A2408885998500000005;
E3969440A681A2408885998500000005
38         
6                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

39         ;*';*";*/;
40         data _null_; e = exist('sashelp.cars');
41         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds
      

42         
43         
44         ;*';*";*/;
45         %put E3969440A681A2408885998500000006;
E3969440A681A2408885998500000006
46         
7                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

47         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
47       !  outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
48         ;*';*";*/;
49         proc sgplot data=sashelp.cars ;
50         	heatmap x=msrp y=horsepower;;
            _______
            180
ERROR 180-322: Statement is not valid or it is used out of proper order.
51         run;

NOTE: The SAS System stopped processing this step because of errors.
NOTE: PROCEDURE SGPLOT used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds
      
52         title;
53         
54         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
55         
56         %put E3969440A681A2408885998500000007;
E3969440A681A2408885998500000007
57         
8                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

58         ;*';*";*/;


59         data _null_; e = exist('sashelp.cars');
60         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      

61         
62         
63         ;*';*";*/;
64         %put E3969440A681A2408885998500000008;
E3969440A681A2408885998500000008
65         
9                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

66         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
66       !  outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
67         ;*';*";*/;
68         proc sgplot data=sashelp.cars;
69         	histogram horsepower / scale=count;
70         	title "Histogram showing HORSEPOWER";
71         	density horsepower;
72         run;

NOTE: PROCEDURE SGPLOT used (Total process time):
      real time           2.35 seconds
      cpu time            0.07 seconds
      
NOTE: There were 428 observations read from the data set SASHELP.CARS.

73         title;
74         
75         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
76         
77         %put E3969440A681A2408885998500000009;
E3969440A681A2408885998500000009
78         
10                                                         The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

79         ;*';*";*/;
80         data _null_; e = exist('sashelp.cars');
81         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      

82         
83         
84         ;*';*";*/;
85         %put E3969440A681A2408885998500000010;
E3969440A681A2408885998500000010
86         
11                                                         The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

87         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
87       !  outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
88         ;*';*";*/;
89         proc sgplot data=sashelp.cars;
90         	histogram MPG_City / scale=count;
91         	title "Histogram showing MPG_CITY";
92         	density MPG_City;
93         run;

NOTE: PROCEDURE SGPLOT used (Total process time):
      real time           0.28 seconds
      cpu time            0.06 seconds
      
NOTE: There were 428 observations read from the data set SASHELP.CARS.

94         title;
95         
96         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
97         
98         %put E3969440A681A2408885998500000011;
E3969440A681A2408885998500000011
99         
12                                                         The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

100        ;*';*";*/;
101        data _null_; e = exist('sashelp.cars');
102        te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      

103        
104        
105        ;*';*";*/;
106        %put E3969440A681A2408885998500000012;
E3969440A681A2408885998500000012
107        
13                                                         The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1

108        ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
108      !  outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
109        ;*';*";*/;
110        proc sgplot data=sashelp.cars;
111        	histogram msrp / scale=count;
112        	title "Histogram showing MSRP";
113        	density msrp;
114        run;

NOTE: PROCEDURE SGPLOT used (Total process time):
      real time           0.22 seconds
      cpu time            0.06 seconds
      
NOTE: There were 428 observations read from the data set SASHELP.CARS.

115        title;
116        
117        ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
118        
119        %put E3969440A681A2408885998500000013;
E3969440A681A2408885998500000013
120

**Comment by tomweber-sas** [comment] 2018-05-30 14:13
@PistonIntJack Thanks for the confirmation on 1,3,5. 
For 2, I believe that the %%SAS is creating a new session, not using the same one as your 'sas' object. There was an enhancement made to that magic, to pass a SASsession object to it, so it shared the one session. I don't see the proc iml in the log from sas.saslog(), so I believe it's using a different one. If you try the following, I think we should see the proc iml in the saslog.
```
# first cell
from IPython.display import HTML 
import saspy
sas = saspy.SASsession(results='HTML')

# next cell (add the 'sas' object on the line with %%SAS and it will use that session to run the code
# any other magics will also use this same session, so IML below will use it too.
%%SAS sas
...

# next cell
%%IML
a = I(6); * 6x6 identity matrix;
b = j(5,5,0); *5x5 matrix of 0's;
c = j(6,1); *6x1 column vector of 1's;
d=diag({1 2 4});
e=diag({1 2, 3 4});

# next cell
print(sas.saslog())
```
We should then see the proc iml in the log from the sas object


number 4. I still see no reason for the error, however, the encodings still don't match, so it's still possible that's causing an issue. Your SAS session is running WLATIN1, which is not the same as your python setting of 'latin1'. Please change python to use 'cp1252' in your sascfg_personal.py. That is the correct value which is the same as WLATIN1.  You should then see this when submitting your 'sas' object:
```
...
SAS Session Encoding  = WLATIN1
Python Encoding value = cp1252
```
Also, let's try running the code differently and see what happens. Can you try this too:
```
# one cell
%%SAS sas
proc sgplot data=sashelp.cars ;
heatmap x=msrp y=horsepower;;
run;

and even this, in a different cell:

# different cell
ll = sas.submit("""
proc sgplot data=sashelp.cars ;
heatmap x=msrp y=horsepower;;
run;
""")
HTML(ll['LST'])

# different cell
print(ll['LOG'])
```

Thanks!
Tom

**Comment by PistonIntJack** [comment] 2018-05-30 15:54
Hi , Tom, thank you for your help.
question 2
I submit the code. But this is an error. I think that I have not %%SAS in the front of the %%IML

![menu saveimg savepath20180530235211](https://user-images.githubusercontent.com/17619159/40731856-8ffbe522-6464-11e8-9912-ba0e8d0d9426.jpg)
![menu saveimg savepath20180530235149](https://user-images.githubusercontent.com/17619159/40731858-94081960-6464-11e8-94ad-209262bfc391.jpg)





question 4
I changed my encoding. But the problem is still exist.
I submit two code in jupyter.  The error is same. I find that the code is wrong in sas(not jupyter).

jupyter log

8                                                          The SAS System
                                                                        2018&#24180; 5&#26376;30&#26085;&#26143;&#26399;&#19977; &#1



57         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
57       !  outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
58         
59         
60         proc sgplot data=sashelp.cars ;
61         heatmap x=msrp y=horsepower;;
           _______
           180
ERROR 180-322: Statement is not valid or it is used out of proper order.
62         run;

NOTE: The SAS System stopped processing this step because of errors.
NOTE: PROCEDURE SGPLOT used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds
      
63         
64         
65         ods html5 (id=saspy_internal) close;ods listing;
66         


![menu saveimg savepath20180530234252](https://user-images.githubusercontent.com/17619159/40731534-d544fdae-6463-11e8-9666-6d363f51d458.jpg)

**Comment by tomweber-sas** [comment] 2018-05-30 16:39
Ok, I see the same error with the %%IML. It doesn't seem to work right with that enhancement to pass a SASsession to %%SAS. It also can't be run if you haven't done a %%SAS first. I'll look into fixing these.

And, I see the problem with the heatmap. http://go.documentation.sas.com/?docsetId=grstatproc&docsetVersion=9.4&docsetTarget=n0w12m4cn1j5c6n12ak64u1rys4w.htm&locale=en
Apparently the heatmap statement of sgplot was added in 9.04m3, and you are running 9.04m2. I just tried it out with M2 myself and see the same error. So, this is an accurate error and has nothing to do with a funny character being transcoded or something. That seemed a longshot, but I couldn't see a syntax error!

I'll open a clean issue for the %%IML, and let Jared fix that. He wrote the magics, so he'll know how that should behave.

It seems like, other than the bug in IML, you're working ok now? 

Thanks,
Tom

**Comment by tomweber-sas** [comment] 2018-05-30 16:50
I've opened #138 to address the %%IML bugs.  FYI.
Tom

**Comment by PistonIntJack** [comment] 2018-05-31 09:58
Tom， I Appreciate it. Thank you for your help.
I am working now. I will follow the issue #138 ;
"heatmap" is a version mistake. I will find my IT teacher to ask what the lastest version in our school.
sorry, I did not  expect the version mistake. 
I have another question. where I can find the History version difference in SAS. 
I only find M5 difference with M4.
http://documentation.sas.com/?cdcId=pgmsascdc&cdcVersion=9.4_3.2&docsetId=basewn&docsetTarget=n0aoxnlicuhy0kn1l0pvgnn2k15e.htm&locale=zh-CN
thank you.

**Comment by tomweber-sas** [comment] 2018-05-31 18:06
No problem, happy to get all this resolved for you. The link I sent above is the doc I saw this in. Here's the bit from that page I read from the sgplot/histogram page (won't cut-n-paste well, but) It's in the NOTE that it states 94m3:


SGPLOT Procedure
Syntax  Overview Concepts Examples 
HEATMAP Statement


Interaction: | Starting with SAS 9.4M4, the number of bins is limited to 100,000. If the number of bins exceeds the limit, the heat map is not drawn. A warning message is written to the SAS log in that case. The limit is specified by the ODS GRAPHICS statement NXYBINSMAX= option, which defaults to 100,000.See NXYBINSMAX=.
-- | --
Note: | This feature applies to SAS 9.4M3 and to later releases.
Example: | About Heat Maps

**Comment by PistonIntJack** [comment] 2018-06-01 09:12
Thank you, Tom. 
I will make great efforts to continue to learn SAS.

**Comment by tomweber-sas** [comment] 2018-06-06 17:08
Happy to help! Good luck in all of your studies, and let me know if you have any other questions or issues!
I'll go ahead and close this now.
Thanks!
Tom

**Comment by PistonIntJack** [comment] 2018-06-13 07:03
Hi， @tomweber-sas， I have another two questions to ask you. I hope that you can help me. thank you.
1.  What does "partition" mean?  what is the defference between hr and hr1?

hr = sas.read_csv(file = "./HR_comma_sep.csv", table = "hr")
hr1 = hr.partition('left')

I have read the function Partition document. But I can not understand the function. 

2. Where is the window that can look over the data? Maybe there is not this window in Jupyter.

![menu saveimg savepath20180613150151](https://user-images.githubusercontent.com/17619159/41335259-c4dbd426-6f1a-11e8-8270-42e0b3e925bb.jpg)


Now I will look over the data by the code.
proc print data=hr;
run;
hr.head()

thank you. Tom

**Comment by tomweber-sas** [comment] 2018-06-13 16:10
@PistonIntJack , I'll have @jld23 address this one, as I don't really know what that does either. 
Tom

**Comment by jld23** [comment] 2018-06-13 18:28
@PistonIntJack,
The partition method is used for splitting your data into training and validation. This is common for predictive modeling where you need a hold out sample to avoid over fitting your model.
The method can do either SRS or stratified sampling and can split the data into separate SASData objects or return a single object with an indicator column.

**Comment by jld23** [comment] 2018-06-13 18:29
@PistonIntJack,
For your second question above about looking over the data, it doesn't exist. If you wanted to contribute something as a jupyterlab extension we would welcome it!!!

**Comment by PistonIntJack** [comment] 2018-06-14 03:21
thank you. @tomweber-sas .
Hi, @jld23 . 
1.  I have read the partition method in the https://sassoftware.github.io/saspy/api.html. But I can not use the function.   Code like the following , I can not find that what is the defference between hr and hr1?
Can you give me a example for the partition?

hr = sas.read_csv(file = "./HR_comma_sep.csv", table = "hr")
hr1 = hr.partition('left')

2. I think that my level can not  contribute something. @_@

thank you @jld23

**Comment by tomweber-sas** [comment] 2018-06-14 15:45
@PistonIntJack I'm not completely sure what you're asking, but try the following and see if it makes sense:
```
cars = sas.sasdata('cars', 'sashelp')
carspart = cars.partition('type', out='carstrain')
cars.head(9999)
carspart.head(9999)
```
You should see that the carspart table only has a representative subset of the data; a training set. You can try other columns to partition on and see what you get. Not to mention other larger data as well.

Tom

**Comment by PistonIntJack** [comment] 2018-06-15 06:39
Thank you, Tom. 
I think that I have understood this function. When I see your code and read the document with @jld23 , I can use this function to  split my data.
Thank you for your help. @jld23  @tomweber-sas

**Closed** 2018-06-19 07:52 UTC
