### ISSUE TITLE
Using df2sd create error

### ISSUE THREAD

**Issue by DevNull83** [sassoftware/saspy#474] opened 2022-07-29 07:59 UTC
Hello,

here is my problem description.

**Describe the bug**
Create a SAS table from Dataframe. The problem is the use of datalines, if the record is more than 32768.

**To Reproduce**
1. Create a pandas dataframe with 3 vars. One var is text with 32767 sas limit text.
2. When you create a sas dataset in your session with the sd2df method the error is catched because if you use the datalines all the variable are stored in one PDV record in the dataset. The file input would be the best choice or the single var reading matched at the end with a merged dataset on rowid key.

**Desktop (please complete the following information):**
 - OS: RHEL
 - SASPy Version: 4.3.0

**Comment by tomweber-sas** [comment] 2022-08-03 14:56
Following up, I was able to restructure some code between the access methods implementations and the main df2sd() method so that I would be able to see about implementing this 'divide and concur' technique implicitly in the method. That all worked out fine, but then when trying to assess the lrecl to see if I needed to do this is not, it turns out that for all numeric columns, I have no idea how long any of those values become in the input stream. I send variable length data across to compress that, instead of SAS's way of all columns being fixed width. Since the numerics are sent as character for SAS to parse, they can be anywhere from 1 byte to who knows. So, I can't know the actual lrecl of any given row; they all vary.

So, I think that me implementing this is a useful enhancement, but I need to figure out how/when since I can't deterministically know when it will be required. I don't like having code 'guess' at things; rather 'know' and be deterministic. So, I'm still thinking on this part.

Were you able to see that this method works for your real use case if you submit the equivalent code as above for your case? 

Thanks,
Tom

**Comment by DevNull83** [comment] 2022-08-03 15:15
Hello Tom,

what method do you mean?

Thanks for your hard work!!!

**Comment by DevNull83** [comment] 2022-08-03 15:22
Actually I tested the vars split datasets and the match-merge between them and it worked, but for my last script I locked the SAS length to 32000 (I have a 767 byte length parachute to avoid the error that works well).
For the fields > 32000 I'll split in more rows...but that will increase a little the number of rows.
It's a compromise to enhance the process strength.

**Comment by DevNull83** [comment] 2022-08-03 15:25
I think you will have to loop foreach variable and matchmerge by id to create the final dataset.
For better performance I will suggest the use of sas hash table lookup for the merge.

**Comment by tomweber-sas** [comment] 2022-08-05 18:21
Hey, just an update. I've been pulled in a number of directions this week, so I'm not finished with this, but I've investigated enough to see that there are a number of other complications with what I thought I might be able to do (though It got me close), as well as seeing some other possible solutions that may have legs. I'm, of course, looking at all 3 of my access methods, as they have some subtle differences and thus different SAS behaviors (that drive me nuts!). So, I have to solve it everywhere and be sure performance doesn't suffer.

Are you using IOM? I don't see anything above that says. I should make more progress on this by next week!

Thanks,
Tom

**Comment by DevNull83** [comment] 2022-08-06 05:05
Hello Tom,

Yes I’m using IOM on Linux.

Thanks.

**Comment by tomweber-sas** [comment] 2022-08-08 19:45
@DevNull83, I've just pushed a branch named `widerows`  which has, what I hope is, the solution to this issue. I still have to do some more testing to prove it all out, but so far, it seems to be the answer. I have changes to all 3 access methods, though I know you're only using IOM. Can you pull this branch and try it; verify with your use cases that it solves this and doesn't cause any regressions as well (and check the performance; I believe it should be equivalent)? I'll continue to validate use cases here too.

Thanks!
Tom

**Comment by tomweber-sas** [comment] 2022-08-10 16:33
I found a case where missing values wasn't handled now, given the new code. So I just pushed a fix for that. Still in the `widerows` branch. It's looking really good, but again, still need to try out more cases and verify it more. Let me know if you get a chance to try out this latest code with your cases.

Thanks!
Tom

**Comment by DevNull83** [comment] 2022-08-12 06:20
Thanks for your work.
I can’t try it until the last week of August.
But when I’ll try it I’ll update this topic.

**Comment by tomweber-sas** [comment] 2022-08-12 13:51
Ok, no trouble, thanks for the heads up. I've tested this with everything I've got and it is solid. Haven't found any other issues. So, I'll go ahead and merge this in and build a new release with it. I also made the same changes in Proc Python (which is in Viya 4), and have been testing there too; I used the same code as in saspy for its df2sd/sd2df methods when I created it. So, when you get a chance, you can just pip install the new version (pip uninstall -y saspy; pip install saspy) and you will have it.

Thanks!
Tom

**Comment by tomweber-sas** [comment] 2022-08-12 17:44
ok, this is now in the current production release; V4.3.2. just FYI.

**Comment by tomweber-sas** [comment] 2022-09-20 15:00
Hey looking to close this one out. Were you able to verify the fix with the current production version?
Thanks,
Tom

**Comment by DevNull83** [comment] 2022-09-20 16:10
Hello Tom,

I tested the current version on my local enviroment and I did not have any issue.
I have to test on production environment, but I required the installation on the Linux server, but unfortunely there is the 4.3.1 version still.
I cannot install by myself the current version, but I need a managed ticket.
I will be able to tell you more in the near future.

Thanks a lot.

Pierluigi.

**Comment by tomweber-sas** [comment] 2022-09-20 16:14
Ok, thanks! If you want, we can close this, assuming it's fixed for you. And when you are able to get it onto the prod system, if you have any issue, reopen the issue. Else, it's fixed and solved. Up to you though.
Thanks!
Tom

**Comment by tomweber-sas** [comment] 2022-09-29 13:41
Closing this one, just to clean up old issues. If you find anything else, just let me know!
Thanks!
Tom

**Closed by tomweber-sas** 2022-09-29 13:41 UTC

**Comment by DevNull83** [comment] 2022-09-29 13:43
Thank you very much Tom!

Pierluigi.
