### ISSUE TITLE
Can't connect to SAS

### ISSUE THREAD

**Issue by rafaellucas3** [sassoftware/saspy#440] opened 2022-02-04 16:26 UTC
Hi,

I am trying to use saspy to skip EG and pull the information directly via python scripts. I can connect to the SAS server via the SAS EG using my windows username and password and the address provided from IT. The address I am connecting to is a metadata server meaning that I should connect to a workspace server instead. After running the 'proc iomoperate' I have identified the workspace server and when I try to connect to it I get an 'access denied' error. I also used the SAS Integration Technologies tool to create iom connections and debug, It seems that I only can connect to the metadata server but not to the workspace server directly. In SAS EG it says that I am connected and authenticated to the workspace server but now when I try to connect using saspy I get denied.  It's a bit confusing why.

What should I do in this case?

**Comment by tomweber-sas** [comment] 2022-02-04 17:00
Hey @rafaellucas3, saspy doesn't interact with the metadata server. The host you need to connect to is where the object spawner is running. That may or may not be the same machine where a given workspace server ends up running. Just depends on how SAS is configured. The port is the the port that the object spawner is listening on for workspace server connections; it listens on different ports for different kinds of server requests. This is the same as what EG does; it connect to the object spawner requesting a workspace server. 

When you ran proc iomoperate, did you run it for the object spawner as well as the workspace server? Depending upon how this is all set up at your site, there could be multiple object spawners and App server definitions, or everything could just be running on one machine.

The other thing you mentioned, about using windows credentials. SAS has a number of different authentication schemes. The usual case is to use metadata user/pw, but there's also the ability to use Integrated Windows Authentication (like single signon from a windows client). I'm not sure how your system is configured. I'd need to see the actual error about access denied to tell what that's about. 

Can you show me the iomoperate output, the actual output (errors) from trying to connect and your configuration? If you don't want to post that here, you can email it to me; either way. Just need to know how your SAS system is configured to get you connecting correctly.

Thanks,
Tom

**Comment by rafaellucas3** [comment] 2022-02-04 17:20
Hi @tomweber-sas! 
Thanks for the quick response.I'll try my best to show here without leaking sensitive info.
Running the  'proc iomoperate' on the address provided by IT on port 8591 gives me the following: 
```
    Object Spawner - ###redacted### (###redacted###.###redacted###)  -> matches the address I connect on EG
        Server class : IOM Spawner
        Spawnable server component : Operating System Services - ###redacted###.
        Operator port : 8581
        PortBank port : 8801
        PortBank port : 8811
        PortBank port : 8821
        Machine name : ###redacted### -> matches the address I connect on EG

    Object Spawner 2 - ###redacted### (###redacted###.###redacted###)
        Server class : IOM Spawner
        Spawnable server component : Operating System Services - ###redacted###
        Spawnable server component : SASApp - Pooled Workspace Server
        Spawnable server component : SASApp - Stored Process Server
        Spawnable server component : SASApp - Workspace Server
        Operator port : 8581
        PortBank port : 8801
        PortBank port : 8811
        PortBank port : 8821
        Machine name : ###redacted### -> the workspace server
```
When I try to identify the workspace server using the  'proc iomoperate' from the docs on the address provided by IT:
```
Foundation repository (###redacted###.###redacted###)

    SASApp - Workspace Server (###redacted###.###redacted###)
        Server class : 440196D4-90F0-11D0-9F41-00A024BB830C
        Logical name : SASApp - Logical Workspace Server
        Server context : SASApp
        Bridge port : 8591
        Machine name : ###redacted### -> matches the workspace server address from above.

BILineage repository (###redacted###.###redacted###)

```
Running the  'proc iomoperate' on the workspace server address I found on the step above gives me the following: 

`30         proc iomoperate
31           uri="iom://###redacted###:8591;Bridge;USER=###redacted###,PASS=###redacted###";
ERROR: Invalid credentials
ERROR: Access denied.
ERROR: A connection to the IOM Server cannot be established.`

The address in red matches the workspace server address I found.
![image](https://user-images.githubusercontent.com/21185198/152573251-345cce03-0846-4d22-86a2-ff777196d071.png)

Thanks for the support.

**Comment by tomweber-sas** [comment] 2022-02-04 17:37
Ok, that all seems to line up. You run that proc against the metadata server, not the workspace server, so the error when trying to point it at the metadata server would be expected. So the 3 'machine names' from the iomoperate output, are they all the same machine? It appears that object spawner 2 is the one you need to connect to. The other doesn't have a workspace server configured. So the iomhost would be whatever that host name is on the object server 2 (Machine name : ###redacted### -> the workspace server) - That's the host of the object server, not the workspace server (of course, they could happen to be the same, but it's the object spawner machine that it's showing). And then the workspace werver port is 8591, as shown in that output.

Oh, I see in the error that you're trying to use the COM access method. Ok, that's a different deal then. Can you use the IOM access method? It works a lot better than COM, and I don't really know what that error implies, off hand for that path. I'll have to research what that com error means.

All you need to use IOM is the path to java. Can you give that a try and see if you can connect?

Thanks,
Tom

**Comment by rafaellucas3** [comment] 2022-02-04 17:45
I don't have java on my machine at the moment. Requested it from IT and now waiting for them to install. I'll update the thread once I try the other method. 
Thanks again Tom!

**Comment by tomweber-sas** [comment] 2022-02-04 17:48
ok, cool. IOM works a lot better than COM, so you'll be happier using it in the long run. Are the credentials you provided to the metadata server, when running the proc iomoperate, the same ones you're providing saspy?

**Comment by rafaellucas3** [comment] 2022-02-04 17:59
Exactly, I tried connecting to the workspace server using the same user and password I use in the EG and metadata server. The EG profile was created using the metadata server address and the server that gets listed is the one pointing to the workspace server (via screenshot). I am able to log-in and use EG to run queries and all.

**Comment by tomweber-sas** [comment] 2022-02-04 18:22
ok, that's good. Then I fully expect this to work when you try IOM. I'm guessing that COM error wasn't about your credentials not being correct, but rather some other error somewhere through the path of the various dependent modules and libraries it uses. I really don't know that much about how it works. It was a contribution; I didn't write it. Pretty cool, but if it doesn't work, then ???

In EG, the profile has the metadata server info in it, while the Connect info (for the SASApp) shows the workspace server info, and in your case, it seems the object spawner and the metadata servers run on the same machine. That's the usual simple configuration. For more complex cases, like Grid, there can be more than one object server (same logical one, but running on multiple, redundant, machines). And they can spawn servers on other machines (any number of them) so as to load balance both the spawner requests as well as the server load across an array of machines.

Your setup looks like a simple configuration. So, I think you have everything correct. I think IOM will work for you when you get java installed. Just change your configuration definition to add the 'java' key, and remove the 'class_id' and 'provider', as they aren't relevant for it.

**Comment by rafaellucas3** [comment] 2022-02-08 15:41
Hi Tom! 
Got Java installed this morning. Here is what I see now: 

- When I try to connect using the address provided by IT (Metadata Server) on port 8561, I get the following error (expected):
![image](https://user-images.githubusercontent.com/21185198/153019725-3a1556e3-88f0-4cab-8a58-2b6e2d8ca7db.png)

- When I try to connect using the address provided by IT (Metadata Server) on port 8591, I get the following error:
![image](https://user-images.githubusercontent.com/21185198/153020152-a26f8b43-aaeb-4882-bba3-38578407fd9f.png)

- When I try to connect using the workspace server address I found using the 'proc iomoperate'  command on port 8591, I get the following error:
![image](https://user-images.githubusercontent.com/21185198/153020777-23237e30-f2a1-48b5-a960-e396c78cfd22.png)

- When I try to connect using the workspace server address I found using the 'proc iomoperate'  command on port 8561, I get the following error:
![image](https://user-images.githubusercontent.com/21185198/153021809-4d017ac5-e737-48a7-b919-2e60c9d21cdc.png)

I checked the password and user I am using and they are the same I am using in Enterprise Guide. To double check, I created a new profile copied and pasted the user/pw from the cfg file and I was able to connect normally in EG. 

What would you suggest at this point?

**Comment by tomweber-sas** [comment] 2022-02-08 16:54
You know, I wonder if the way your IT has this configured is to use [Token Authentication](https://go.documentation.sas.com/doc/en/bicdc/9.4/bisecag/n0rhb6yftn8srbn1wqxpg2s0fzfd.htm)? That would probably account for the invalid user/pw when connecting to what is probably the correct machine for the object spawner. That also seems to match up with your statements about only connecting to the metadata server and using your windows credentials; I think, because I've not ever had a setup like that here such that I have actually seen it in action. But, this sounds like how it might be set up at your site. 
Do you have SAS Management Console? That's used to connect to the Metadata server. You can use it to see what the authentication scheme is for the workspace server; [step 3 here](https://go.documentation.sas.com/doc/en/bicdc/9.4/bisecag/p06o3ymf2cuw16n1cmyi47t9icsn.htm).

The bad news is that saspy can't use this form of authentication, as it doesn't connect to the metadata server. But, lets see if that is the problem or not. Though, given you only have a couple of machines, it seems that you have the right info in some of those attempts, and wrong user/pw would probably be error that would be produced for that case - I don't know for sure, but it seems likely.

**Comment by rafaellucas3** [comment] 2022-02-08 17:17
Unfortunately I do not have this level of access. I am not from IT just an over pro-active analyst lol. Thank you for your time and effort to solve my problem. I might just go with automating EG with VBA then :( and then reading the files with Python.

**Comment by tomweber-sas** [comment] 2022-02-08 17:59
SMC is just a client UI tool for interacting w/ metadata; it doesn't give you any permission you don't have. it's just way easier to look at metadata w/ it than using proc iomoperate. But, if you don't have it then you don't have it. I've been playing w/ iomoperate and think we may be able to see the auth mechanism, just by adding 'verbose' to the query for the workspace server. I'd rather not give up until we see if that is really the problem or not.

Can you retry your workspace query adding verbose, like below? I see an extra piece of info `AuthService : ` when I run it that way, and I think that identifies the authentication mechanism (I'm guessing; see what it says). 

'''
proc iomoperate
  uri="iom://omrhost.abc.xyz.com:8561;Bridge;USER=omruserid,PASS=omrpasswd";
  list DEFINED FILTER="- Workspace" VERBOSE;
quit;
'''

Thanks,
Tom

**Comment by rafaellucas3** [comment] 2022-02-08 18:50
Hi Tom,

I ran the command and this is the result: 
```
    SASApp - Workspace Server (###redacted###.###redacted###)
        Server class : 440196D4-90F0-11D0-9F41-00A024BB830C
        Logical name : SASApp - Logical Workspace Server
        Server context : SASApp
        EnableSACS : True
        AuthService : Host
        Bridge port : 8591
        Machine name : ###redacted### <- the workspace address we found 
        Command : /sas/serverconfig/Lev1/SASApp/WorkspaceServer/WorkspaceServer.sh
        LBStartSize : 0
        RecycleActivationLimit : 50
        LBMaxCost : 500
        LBStartupCost : 200
        MaxClients : 10
        AllowReconnect : True
        MaxReconnectTimeout : 60
```

Thanks again for all your help!

**Comment by tomweber-sas** [comment] 2022-02-08 18:52
Well, that shows `host` as the Auth service. If it were Token, I was expecting to se `Token`, though there's no doc that says what it would say, so I was expecting something else. I'll set up a Teams chat so we can look at this a little more.

**Comment by tomweber-sas** [comment] 2022-02-08 20:07
Let's try sspi with the sspiauth.dll.

**Comment by tomweber-sas** [comment] 2022-02-08 21:16
And, of course, I just thought of the fact that sspiauth.dll won't be in your server deployment since those are linux. It would need to come from a windows install. Let me check with Tech Support to see if they have a download for this that I don't happen to know of. Then if you can get it from them, you'll be good to go to try this out.
Tom

**Comment by tomweber-sas** [comment] 2022-02-08 21:41
Tech Support can put the dll on the download site they have, so you can download it. What was the full version of you're server (it's in the output we were looking at). 9.3 maint ????  version?
Thanks,
Tom

**Comment by rafaellucas3** [comment] 2022-02-08 21:45
Hi Tom,
This is the version I see on the properties of the Server on EG (9.03.01M2P08152012): 

![image](https://user-images.githubusercontent.com/21185198/153080760-7ccea462-b0a2-4acc-9e34-a361b1fcaa76.png)

Thank you so much. 
Raf.

**Comment by tomweber-sas** [comment] 2022-02-08 21:50
Sweet, I'll send you a link once we get the right file out to where you can download it!

**Comment by rafaellucas3** [comment] 2022-02-10 14:17
Hey Tom! 
I got the file but when I run: 

`import os 
print(os.environ["PATH"])
os.environ["PATH"] += "#path to sspiauth.dll folder#"`

The path gets added to my USER path environment not the SYSTEM path environment. Since I don't have admin rights, I can't change my system environment. I will reach IT and see if they can add it for us for testing.
Thanks for all the support! You are amazing.

**Comment by tomweber-sas** [comment] 2022-02-10 14:20
That's ok, that sets it in the Python environment, which is all it needs. To set it in system make it available by default, but setting it in your config, make it be there when saspy needs it. Give it a try and set sspi to True and let's see if this is even the problem!
Thanks,
Tom

**Comment by rafaellucas3** [comment] 2022-02-10 14:34
Here you go: 
![image](https://user-images.githubusercontent.com/21185198/153429244-e5c70549-7ee7-4eaa-8d7f-b5134576f1db.png)

**Comment by fgenoese** [comment] 2022-02-11 16:34
Having a very similar situation here. Connection from SAS EG works, saspy fails. (AuthService is Host for me as well)
Tried the following winiom config combinations:

- metadata server IP at 8561: complains that I am trying to connect to the metadata server
- metadata server IP at 8591: wrong user / password
- workspace server IP at 8561: complains that I am trying to connect to the metadata server
- workspace server IP at 8591: wrong user / password

Curious to see whether there will be a solution.

**Comment by tomweber-sas** [comment] 2022-02-16 15:46
Hey @fgenoese, the errors about the metadata server are correct, saspy connect to a workspace server, not the metadata server. For the uesr/pw error when connecting to the correct host/port, What's unfortunate is that for AuthService=Host, there are still a few different schemes that fall under that, and none of those details are provided by the query. I just got back from vacation today, but when I was looking at this before I left last week, I found a way to try to query those details, but it fails w/ not enough permission, which is what I expect non-admin users would get. So, do you know what authorization scheme your workspace servers are set up with?
For this thread, I've been guessing that it may be IWA, though I have no way to discern that w/ what we can gather from the user side. So, we were just trying to use it and see what happens, but ran into issues w/ getting the required sspiauth.dll file and getting it into the path. Trying to ask IT/SASadmin how it's configured is the (should be the) easy way to know, but that isn't always available. 
Do you know if yours is configured to use IWA, and have you tried that?
Tom

**Comment by fgenoese** [comment] 2022-02-16 17:55
Thanks for the reply. Could you elaborate what kind of authorization schemes exist and which (at least in theory) should work with saspy?  (I am no IT guy) 
I will then pass on the question & information to our SASadmin.

**Comment by fgenoese** [comment] 2022-02-17 08:33
Thanks! The folder `C:\Program Files\SASHome\Secure\ccme4` is in my path, but `sspiauth.dll` is not in there. Hence, connecting with `'sspi' = True` fails. How can I get that file?

**Comment by tomweber-sas** [comment] 2022-02-17 16:12
@rafaellucas3, have you been able to get the directory added to your path so that the file is being picked up? That still seem strange that having it in the Python env didn't find it. It does seem most likely that they are using IWA for the workspace server, so if we can get that found, I'm expecting it to connect.

**Comment by rafaellucas3** [comment] 2022-02-17 21:21
Hi @tomweber-sas,
Still waiting for IT...
I will call them and follow-up.
Sorry.

**Comment by tomweber-sas** [comment] 2022-02-17 21:36
No trouble; on your timeline :)

**Comment by tomweber-sas** [comment] 2022-02-23 18:10
Hey, I wanted to post here, some of what I've been working offline with. About downloading the sspiauth.dll and just having it on your system. Both of you have done that and still get the message about it not bein found, even though it's in your path. I have to believe that is an issue w/ some OS dependency not being found, or the specific version of it not being found; different levels of windows, different system32 libraries. This would be that it was found, but other dependencies couldn't, so the end effect was it couldn't be loaded, thus that same generic error. I found a tool that shows the dependencies of the dll, and there aren't any that are from a SAS install; they are all windows system dependencies. 

After talking w/ one of our TS guys who knows the most about IOM and stuff, it seems that simply grabbing whatever version of that dll and sticking it on your system, may or may not actually work. I tried this on one of my machines at home, which didn't have any SAS software on it, and downloading the dll from the tech support site (and installing python, saspy and java), provided it to work (the dll was found and used). But, this is a new win 10 system, with the latest OS. 

I don't know the details of how this dll is built and linked, but I have to believe that it's an incompatibility between the version you downloaded (whatever version we put out there for you) and the OS your on. Best guess at this point. Unlike how (before the IOM jars were allowed to be in the saspy repo) you could just go copy the 4 required jars to your machine, from any SAS install (win or linux), to whatever client you had (win or linux or mac), and that worked fine, a dll isn't a jar, and it does have specific system requirements to be able to run; java's independent of this. There's also no way to 'install' that dll other than to install windows SAS. There's an Integration Technologies stack that can be installed independently, and that's is what EG uses to interact w/ SAS servers and do authentication, it doesn't use the java IOM client, so the dll isn't install with it. The only reason I have it on my system here at work is from a windows SAS install on my PC.

So, I'm at a loss as to how to get you a version that would work (I assume there is some version of the dll somewhere). I'm thinking that opening up a Tech Support ticket for this is the next step (let me know the ticket and I can help on the inside here). There's one TS note on found that says to do this, though I'm not completely sure how they would come up with a version that works; gotta know the version of windows you have ... I expect? https://support.sas.com/kb/63/738.html
Seems like maybe they would know how to get you the right version that can work from your system. Let's give that a try.

Again, this won't help if your workspace server is configured for Token Authentication, only for the IWA configurations. 

Thanks,
Tom

**Comment by tomweber-sas** [comment] 2022-03-08 15:33
Oh, I typed this in over a week ago but never hit send. Posting now anyway. Have either of you had any progress on your end?




One more follow up for today. I was able to finally find and access this dll (sspiauth.dll) from builds for releases from the past decade, and for both 32bit windows and 64bit (probably the only case anyone's running these days). I used the tool I found to show the dependencies and they are the same for each of these from the one for 9.40 (M0 so to speak) to the version built for 9.40M8. If this were Linux, it'd be easy to see what the problem was, but this stuff on windows doesn't lend itself to that.

I tried each of these different dll's (different sizes, ..., but the same dependencies) on my home 'clean' system where I copied these and swapped each of them in to see if IWA could work. Each one worked without issue. That is except for the one that was built for a 32bit system (again, same dependencies in the list, but it didn't work). I expected it to not work, and I got the same error in that case about the module not being found (yes it was, it just didn't load and function). So, again that error is sort of a catch all, not a truly accurate msg.

`So, what version of windows are each of you running?`

Since this last guess about the dependencies (based upon how .so's (the .dll version on linux) work, and or fail based upon dependencies), I don't see that really being the actual problem here - the 3 windows/system32/xxx.dll dependencies are the same in all version of this dll that I've tried. But, they are different, different sizes per build ...  So there's still something different that could still be the cause, though I still don't know what that would be. In all the cases I've tried, I'm running on w Win 10 Pro OS. Heck, it could be the 3 windows (dependent) dll's that have some issue and are the actual problem on your systems, but again, I just don't know at this point. 

Tom

**Comment by tomweber-sas** [comment] 2022-03-28 13:40
Any update on this for either of you? 
Thanks,
Tom

**Comment by fgenoese** [comment] 2022-03-28 15:57
No reply from my IT regarding your question about the Authentication Mode (Host, Token, or Prompt).

**Comment by tomweber-sas** [comment] 2022-03-30 13:52
Ah, and if I remember right, we thought it was probably using the Token auth? Which is the only one SASPy doesn't support, as it's  based upon interactions with the Metadata server. Have either of you reached out to Tech Support to see if there's a version of the file specific to your operating system that could be the issue? There was that TS Note I posted in an earlier post, above, showing a dozen or so different version of Windows. That 'not found' error is a catch all, as I described above when testing out on my home system which has no SAS on it. The actual DLL may be the problem if it's not built for the specific version of windows you're running; at least that's all that I'm left with as a guess. 

What do you guys want to do with this issue? Keep it open and continue to see what TS can do? I don't know of anything else I can do from my end. 

Thanks!
Tom

**Comment by tomweber-sas** [comment] 2022-05-03 19:34
Anything else I can do for this? I just had an issue #455 where sspiauth.dll wasn't being found, and the user couldn't update the system path (no permission). What they did that made this work was just copy the sspiauth.dll to a directory that was already in the system path, and they obviously could copy a file into. Then it was found and worked. That made me think of you guys! Seems worth a try, in case the dll you downloaded actually works, and somehow it really wasn't being found???

**Comment by tomweber-sas** [comment] 2022-05-17 15:56
Guys, I'm going to close this up as there's nothing else I can do. Above is a possible workaround for not being able to put the dll in the path; another user had the same permission issue and setting it in python using os.environ['PATH'] didn't work for them either.
I've never seen that not work, but again, could be some weird windows issue. The only other thing is the dll not being right for your version of windows, and that's gonna have to go to TS (the TS note on that is a link up above), to see about getting the correct version for your version of windows. 
The other case of Token Authentication can't work since saspy doesn't interface to the Metadata server directly; that's the one auth mechanism saspy can't support.

So, I'm closing this since it's been sitting here for some time and I can't really do anything else to fix it. But, just let me know if there's more you want to pursue on this. I'm always happy to help. Just don't have the final answer on this one.

Thanks,
Tom

**Closed by tomweber-sas** 2022-05-17 15:56 UTC
